### ISSUE TITLE
Eloquent latest(), add order by id on top of order by created_at

### ISSUE THREAD

**Issue by godbout** [laravel/ideas#1001]
This has been referenced in https://github.com/laravel/framework/issues/22899 but got closed under the reason that the version of Laravel used was 5.3, but this is still relevant up to 5.6.

In my tests, I create 2 invoices, and test some things based on the latest invoice created. The tests fail. The reason is that both the invoices, although created in a certain order, have the same created_at.

I am able to solve that issue in several ways (specific a different created at, or add the id ordering within my own code). Furthermore, it will probably never happen that 2 invoices for the same client are created exactly at the same time. Still, something doesn't feel right to me in how the ```latest()``` function works.

So I'm referring it here.

Any valid reason not to add order by id on top of created_at?

I can do a PR. Just asking because I might be missing something here, and maybe there's a valid reason that it works the way it currently works. Thanks.

**Comment by godbout** [comment]
Just for info, this is how I solve it for my own case currently:

```
public function getLastInvoiceAttribute()
    {
        return $this->invoices()->latest()->orderBy('id', 'desc')->first();
    }
```

**Comment by sisve** [comment]
Would this still work if I use another type of primary key than an auto-incrementing integer? Like a random uuid?

**Comment by godbout** [comment]
Good point. Currently it works for no case at all though. I believe handling some is better than none. We could maybe test the column type?

**Comment by sisve** [comment]
I do not think that Laravel has that type of metadata available. The only way would be to query the database to see if it is auto_increment (or using postgresql's ranges). I could be using an integer column where I've assigned random values.

I believe this is domain logic. It's your domain to specify the precision of the datetime column, a nanosecond precision would be less susceptible to this issue than date precision. And it's domain logic that determines what type of values are stored in the id column. As such, the logic should also be in the domain to handle, not in the framework.

**Comment by godbout** [comment]
I see. Still, something doesn't feel right here. Not sure yet how to handle it.

**Comment by tomschlick** [comment]
I agree with @sisve here. By default I wouldn't want`latest()` to interact with the `id` column. There would be no good way to remove that in the case of uuid based columns or if you wanted to base your query on the `updated_at` column.

You could create a secondary method such as `latestById()` and add it to a base model or PR that into the framework.

**Comment by godbout** [comment]
Yeah, you guys are right.

What about something like ```latest(['created_at', 'id'])``` or ```latest('created at, id')``` to add sorting on multi columns?

**Comment by 36864** [comment]
At that point you're just aliasing `orderByDesc('created_at', 'id')`.

**Comment by godbout** [comment]
Well, ```latest()``` is itself an alias to ```orderBy()```. The point is, something doesn't feel right (at least for me, and it seems 2 others users out there) about that ```latest```  that doesn't return the latest record when ```created_at``` are the same. I'm just trying to find a way to make it more intuitive. Like I was expecting to be able to give the both columns as options to ```latest()```. If that seems dumb to many people, then maybe I'm the one missing something. Gonna let some days pass, and if I still feel like it's I might do a PR anyways. Thanks for the comments!

**Comment by Patryk27** [comment]
Nowhere it's said that `id`s have to be auto-incrementing integers [1] - that's why I don't think making `latest` method use that field is a reasonable decision.

Framework should only utilize what's predictable and standardized - `id`s aren't and won't ever be.

That being said, I think there should be a possibility for a model to override the default behavior of this method (either by a property or some method).

[1] they can be UUIDs, strings or even floats, if someone wants and that makes sense in the domain.

**Comment by michaeldyrynda** [comment]
`latest()` (and it's inverse `oldest()`) are just convenience wrappers for the `orderBy()` method, defaulting to using the `created_at` column. This also makes the assumption that your table is using the default `timestamps` fields (`created_at`, `updated_at`).

Any further scoping around how you actually sort your results are business-specific, and as has been pointed out already, there are already tools in the framework that allow you to easily implement this.

In terms of your tests, you can just sleep between inserts, or manually specify the values.

Tying in other columns to the `latest()` method makes too many assumptions about the schema of literally thousands of different applications.

**Comment by imbrish** [comment]
@godbout latest accepts column to order by, so in your case you could just do
```php
return $this->invoices()->latest('id')->first();
```
There's no need to sort by `created_at` if you sort by `id` anyway.

As things are now this would be difficult to implement, because `Illuminate\Database\Query\Builder` has no knowledge of models. But then look at https://github.com/laravel/internals/issues/1015. If we override `latest` and `oldest` in `Illuminate\Database\Eloquent\Builder` then we could look at model's `getIncrementing()` and `getKeyName()` to make these methods a bit smarter.

**Comment by rcubitto** [comment]
IMO, ordering by ID doesn't feel right. The same for thinking that "a record was created afterwards because its primary key was greater".

The solution I'd go with, is setting different `created_at` values in your tests. As you said, there's minimum chances of 2 records being created at the exact same time, so this idea makes more sense to me and represents domain logic in a better way.

**Comment by chrisijoyah** [comment]
@godbout This is exactly what I was experiencing and it took me a while to figure out what was happening. I had generated some seed data, and they all had the same timestamp. I had an API endpoint that was returning this data and using the `latest()` method. I noticed that it would shuffle the ordering each time I called it. You can imagine the problems this caused in my Vue component, where I had a 'load more' method that would append the next result set to an array, it was causing duplicate keys to be added due to the reshuffling. I would have thought the fallback would be to order by ID if all the timestamps were the same.

**Comment by godbout** [comment]
@chrisijoyah I sympathize obviously, but I think most people are correct in this thread and there were ideas that I didn't foresee. I think as @imbrish said, using `->latest('id')` should be enough (I haven't tested it though).

Thank you all for the comments. I close.

**Comment by MHafet17** [comment]
error hahahah

**Comment by bjuppa** [comment]
This is interesting! I stumbled across the same problem of identical timestamps and ordering this week and solved it with specific sorting scopes for my models. But it made me think... there must be something eloquent could have to help us here!

I really don't like to use `->latest('id')` where the key is hardcoded—an outside caller shouldn't need to know the column names.

I like @tomschlick's idea of a new separate method `latestById()`, that could order by the model's `getQualifiedKeyName()` internally. Maybe it could be called `latestIncrementingId()` just to be more obvious? It could sort by timestamp first (if model has timestamps) and key second... 🤔 

Another idea is to just add `orderByKey()` and `orderByKeyDesc()` to the eloquent builder. It's simple and does exactly what it's named. [Eloquent builder method `enforceOrderBy()`](https://github.com/laravel/framework/blob/16d759d2492250ea503ea8fce4412bb5155e496e/src/Illuminate/Database/Eloquent/Builder.php#L673) (used internally by `chunk()`) already does a similar thing, but with conditions we wouldn't want here.
