### ISSUE TITLE
migrate:fresh should drop tables in all databases

### ISSUE THREAD

**Issue by cweiske** [laravel/ideas#1026]
During development, `artisan migrate:fresh` is used to re-run all migrations on a clean database.

When using multiple databases, `migrate:fresh` fails for this use case because it only drops tables on the default database - see https://github.com/laravel/framework/issues/22681, https://github.com/laravel/framework/issues/21009 and https://github.com/laravel/framework/issues/21063

Please make `artisan migrate:fresh` drop the tables on all databases.

**Comment by phroggyy** [comment]
Just use the `--database` argument

**Comment by cweiske** [comment]
`--database` does not help because it drops the tables on one database (only one db name supported!) and then re-runs *all* migrations, which means migrations for all databases.

- `./artisan migrate:fresh --database=A` drops tables from A, but runs migrations for A and B.
- `./artisan migrate:fresh --database=B` drops tables from B, but runs migrations for A and B.

In the end, migrations are executed for all databases - and that will fail, because either A or B will still contain tables.

**Comment by rs-sliske** [comment]
allowing the database param to take multiple databases seems the most sensible way of doing this imo

personally i work on a few projects where not all the databases are managed from migrations in the laravel project (integrating with old systems which dont have (good) apis by reading directly from the database).

**Comment by cweiske** [comment]
My goal - as described as the use case above - would be to be able run `migrate:fresh` and be done with it.

If the `--database` parameter would support multiple databases, how does it then make sure that only the migrations for the listed databases are being run? That's the main problem IMO: Migrations being run on databases that have not been cleared.

**Comment by mfn** [comment]
I think this would require a slightly different default [`config/database.php`](https://github.com/laravel/laravel/blob/master/config/database.php).

With how things work right now, you you only have to adapt the `mysql` and/or the `default` and be done => it works.

If commands like `migrate:fresh` suddenly consider all defined in `db.connections`, it would easily break/confuse users experiences (assuming they didn't remove/disable the other defaults => which as of now isn't required).

**Comment by saifulss** [comment]
Perhaps let --database accept multiple databases, as was suggested above. Whatever UX issues there may be, it'll be understood that if the user passes that database value, he expects that database's tables to be dropped.

Then finally migrate:fresh can be useful for projects with multiple databases.

For now, I find myself having to make my own command to drop tables from multi-databases. Which feels meh cos I know migrate:fresh is so close to getting it done.

**Comment by hailwood** [comment]
Making `migrate:fresh` by default drop all databases will confuse users for the reasons stated by @mfn, and honestly feels like an exception rather than the most common use case.

Updating `migrate:fresh --database` to take multiple databases seems logical, we could also add a `--all-databases`/`-a` flag which would then run over all defined database connections.

**Comment by brentli1** [comment]
I'd like to request to reopen this.  As recently I've entered into a project that requires multiple databases and being able to at least add multiple databases to the database flag would make the dev process much smoother.

**Comment by drbyte** [comment]
Perhaps use the proposed trait posted by @sepehr in the issue linked above: https://github.com/laravel/framework/issues/21063#issuecomment-360616841

ie: Battletest it in your own use, and then collaborate on a PR.

**Comment by luizguilhermefr** [comment]
A `--all` would be perfect. As stated by @cweiske using `--database` option is not suitable.

@taylorotwell would you reopen this?

**Comment by ryanpaulfyfe** [comment]
+1 for a re-open and consideration

**Comment by Atiladanvi** [comment]
I consider this question fundamental to able a developer manage your database schemas. I have to write a extra script.My suggestion: If the migrations class have a connection atribute the script could get a connection name and drop tables. If connect are null drop in default connection.

**Comment by JoelWigren** [comment]
I have the same problem, even worse by using Lumen. I ended up writing my own command instead, pretty ruffly described: I peaked the command _artisan:fresh_ thats is very well commented (thanks to author!), it can be found at _vendor/illuminate/database/Console/MigrateCommand.php_. As the comments points out the migrate:fresh only calls other "migrate" commands and then seeder if needed. So I created my own command as docs describe [https://laravel.com/docs/5.8/migrations#creating-tables](url). In my command I used _config('database.connections')_ to get all the connections and created a loop. `public function handle() {
        $servers = config('database.connections');
        foreach($servers as $server => $config) {
            if ($server == 'server') {
                continue;
            }
            config(['database.default' => $server]);
            $this->call('migrate:fresh');
        }
    }`

And as you guys can see I filter out connections not used by tenats, go easy on the namnig. This is my "test out" application where I am trying to work out the hard parts :) There will be an issue when creating migrations for tables not used by tenats but only "badly named server connection", this can be fixed by wrapping the Schema::create with

`if (! Schema::connection('server')->hasTable('clients')) {
Schema::create(...}`

Hopefully this will help someone!
And yes, my command was named **migrate:all**

**Comment by EfrenRobles** [comment]
Hello there, I know this is old, but I found a solution I hope this work for you, this work for me like a charm on lumen but this should work for laravel too.

In the composer.json
add a script like

`"scripts": {
       ...
       "migrate:fresh": [
            "@php artisan migrate:fresh --path=/ --database=database_b",
            "@php artisan migrate:fresh"
        ],
       ...
}`

and use it with composer

λ composer migrate:fresh

`λ composer migrate:fresh
> @php artisan migrate:fresh --path=/ --database=pgsql_big
Dropped all tables successfully.
Migration table created successfully.
Nothing to migrate.
> @php artisan migrate:fresh --seed
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2020_03_27_234207_create_countries_table`

Let me explain:

@php artisan migrate:fresh --path=/ --database=database_b
this is only to drop all tables with a path where there are not migrations and select the second dabase.
if you have migration files for this database just add it in the `--path` param.

`@php artisan migrate:fresh --seed`
this will work in the default database, ex: database_a

**Comment by luizguilhermefr** [comment]
It's awful how Laravel still doesn't have this.

**Comment by gabrieldarruspe** [comment]
As a workaround, this did the trick for me:
`php artisan db:wipe --database ConnectionA`
`php artisan migrate:fresh --database ConnectionB`
