### ISSUE TITLE
Laravel optional route parameters + PHP 7.1 Nullable Types

### ISSUE THREAD

**Issue by OzairP** [laravel/ideas#1039]
Hello 👋,

## Current Behaviors
I'm here to propose new syntax to the Laravel routing and modifying existing behavior for the optional parameters.

Currently optional types are declared as
```PHP
Route::get('/image/{file}/{height?}/{width?}', ...);
```

Starting in PHP 7.1, Nullable Types can be declared by adding a `?` in front of the type. This states that `NULL` values can be accepted.

```PHP
public function show (string $file, ?int $height, ?int width) {

}
```

## Proposal 1: Allow `?` to be moved in front of parameter names
For consistency with PHP 7.1 optional parameter, the following syntax should be allowed in Route declaration.
```PHP
Route::get('/image/{file}/{?height}/{?width}', ...);
```

To maintain backwards compatibility, both syntax should be allowed to "idiot proof" optional route parameters.

## Proposal 2: For missing parameters in optional parameters, pass `NULL`
Currently, if the parameter does not exist (ex: `GET /image/bar.jpg`), when the controller is invoked, the `$height` and `$width` parameters will not be passed to the function. So we must default it to `NULL` or any other default value. Therefore we cannot use nullable types in the method signature since `NULL` is not replaceable by `void`.

To maintain backwards compatibility we can Reflect the function to see if it accepts nullable types. This will allow for more descriptive controller method signatures, and fully use PHP 7+ features.

![Code](https://static.ozairpatel.com/yeuor.png)

**Comment by sisve** [comment]
> For consistency with PHP 7.1 optional parameter, the following syntax should be allowed in Route declaration. [...]

The routing system has never had any goals to match the php 7 typehinting system. Having two syntaxes for identical things sounds wrong.

Regarding allowing null to a nullable parameter; this can be done with changes to the controller dispatcher. Just send a PR with appropriate tests. Keep in mind that it would be nice if the solution didn't crap out on PHP 7.0 since 5.5 LTS supports it, and we don't want to add unnecessary complexities for package developers to target both 5.5 LTS and 5.6 (... and 5.7, and 5.8)

**Comment by taylorotwell** [comment]
See above.

**Comment by DevChristians** [comment]
Hi dev's, why syntax can't be like this?
`laravel.app/full?width=800&height=500`
