### ISSUE TITLE
User verification by email

### ISSUE THREAD

**Issue by CDNRocket** [laravel/ideas#1042]
The Framework already adds nice authentication mechanism out of the box.
But I think that the email verification should be added and configurable in config/auth.php.
Without the need to use 3rd party packages or write custom code for this very common feature.

**Comment by imbrish** [comment]
As far I remember existing `Illuminate\Auth\Passwords\DatabaseTokenRepository` originally used for the forgotten password feature, can be neatly reused for the email confirmation. Unfortunately this required some insight into internal workings of the framework which new developers may lack. 

Because the email confirmation is one of the first things many new users may want to do, I think it's reasonable to have it out of the box. Alternatively `DatabaseTokenRepository` could be slightly refactored to make it more flexible and easier to use. Then we should also mention it in the docs. Nice way to teach some about the framework and reusability of its components too!

**Comment by taylorotwell** [comment]
I think the new signed URLs feature would probably work well for this. There is no need for an additional database table to store tokens. If someone wants to take a stab at a implementation I can review it for 5.7.
