### ISSUE TITLE
An open letter to: Taylor, or whomever is closing ideas

### ISSUE THREAD

**Issue by garygreen** [laravel/ideas#1051]
Over the past few hours the ideas repository has gone down from around 600 ideas to currently 288.

It's good this repository is being "cleaned" as it were, from stale discussions or out of date / no longer applicable ideas. However, the majority of ideas that have been closed have been done so without any form of communication to suggest whether:

   a) A PR is welcome
   b) Idea is stale and hasn't had much interest / Re-Open if interested again
   c) Idea has been fixed / addressed in Laravel already
   d) Idea will not be considered / Unlikely to be accepted

Simply closing the PRs without any clear intention show's lack of empathy for those who have spent time coming to this repository and sharing their idea, especially when well thought out and have a lot of traction.

From my own personal perspective, it makes me feel like I shouldn't bother drafting anymore ideas or contributions anymore - what's the point if they aren't going to be taken seriously or even warrant a  proper response?

I understand the repository was getting out of hand and replying to each one would take a considerable amount of resources, but surely there is a better way to manage the issues than blindly closing them without due care. A simple tag on each repository to show as above would suffice in making people feel like they are being heard.

**Comment by laurencei** [comment]
> but surely there is a better way to manage the issues than blindly closing them without due care.

Not sure if you saw - but yesterday Taylor put up an ad for a "Open Source & Community Liaison". The job ad is here: https://medium.com/@taylorotwell/laravel-is-hiring-again-246b502f7dcb

To me, that shows a significant financial investment by Taylor into the management of this repo (and all others).

I'm not agreeing or disagreeing with what you said - I'm just pointing out that a proper solution to the workload of managing so many issues/ideas/PRs etc is coming, and everyone will benefit when it starts.

**Comment by deleugpn** [comment]
What Laurencei said.

**Comment by garygreen** [comment]
Which is exactly why I haven't directed this to just Taylor but also to whomever will be closing the ideas.

It's great that a significant amount of investment is being made to help manage the repositories, but I also believe you should lead by example - closing issues without due care doesn't set a good one, at least to me.

With that said, I do have faith that whoever will take over the responsibility of the issues will be someone like us who is deep in the Laravel community and will manage the issues well.

**Comment by denaje** [comment]
IMO, what is needed more than anything else is simply _explanation_. Taylor and friends close PRs and issues frequently with little to no explanation, even after being explicitly asked for it. I recently had a PR closed by Taylor with no explanation given, even after I made a case that (I thought) was decent. I would like to at least hear a rebuttal of my case showing why I was wrong or what some alternatives might have been.

I've also seen that he closes many PRs with "No plans to add". It's the same deal...why? What is going through his mind when he decides to add or not add a feature? I'm not saying he needs to write a novella on every PR or issue, but at the very least open a public discussion somewhere (perhaps here, perhaps in the docs) where we the would-be contributors can gain some insight into the decision making process so that we can attune ourselves to his way of thinking before spending valuable time crafting contributions only to have them rejected.

**Comment by taylorotwell** [comment]
The closes are mainly B,C,D. If they are A I usually indicated it in the issue. I don't plan to type a formal response for each issue close. If it makes people feel better I can copy and paste the exact same wording for every close but I'm not sure if that is much better.
