### ISSUE TITLE
Authentication improvements: 2FA & Password-less login

### ISSUE THREAD

**Issue by barryvdh** [laravel/ideas#109]
While the default Laravel authentication is pretty nice and secure, perhaps it would be benificial to add some improvements by default.
### Two Factor Authentication

This is already in Spark with Authy (I think), but could also use the free HOTP/TOTP algorithms, like https://github.com/antonioribeiro/google2fa by @antonioribeiro to create free 2FA.
Perhaps this could be abstracted as some sort of driver system, eg. define the available 2FA methods in the config, store the method on the user column and handle the 2FA. The scaffolding and authentication traits could do the boring work, to make it easier for people to implement.
### Password-less login

With all the password leaks of late, storing passwords could be safe in Laravel, but with password re-use, passwords for Laravel sites can still be compromised (although not our fault). An alternative could be password-less login: https://medium.freecodecamp.com/360-million-reasons-to-destroy-all-passwords-9a100b2b5001
An example is also created by @mattstauffer here: http://blog.tighten.co/creating-a-password-less-medium-style-email-only-authentication-system-in-laravel
This could be similar to the current password-reset implementation. This would again be optional, but would give developers the option.

I guess these 2 methods could be implemented independly, but they could be combined I guess (eg. passwordless login, but still use 2FA code)

While both options can be perfectly created by 3rd party code, perhaps this would give Laravel some bonuspoints for security and push for a safer internet :)

**Comment by JosephSilber** [comment]
What does it mean to have 2FA without a password? What's the 2nd factor?

**Comment by tomschlick** [comment]
I like this idea a lot. A first party collection of traits to handle the most common approaches to auth would not only make your average application more secure, but would put Laravel ahead of other frameworks who solely leave it to packages.

If these were done as traits to the model / auth controllers it would make it super simple to use it where you need to or change it out for a custom solution if need be.

**Comment by antonioribeiro** [comment]
@JosephSilber, imo a link sent by e-mail is the "new password" ;)

And 2FA isn't (usually) tied to a password but to a user account, and changes as time passes. So it would be as simple as:

1 - User types the e-mail on a login form.
2 - System identifies the user account and creates a new token (temporary password) and send an url with it via e-mail (1st factor)
3 - User clicks the url
4 - System identifies the user account and shows a 2FA form (2nd factor).

**Comment by antonioribeiro** [comment]
I love the whole idea, but this "e-mail is the new password" it's not me saying it, I still have some (very few at this moment) reservations about tokens sent by e-mail, simply because we cannot be sure the e-mail will arrive "on time".

MTAs are still not really reliable and as fast as we may think they are. It's cool, but I have more confidence on a instant messenger, like Telegram, Slack, Facebook, Skype, or even WhatsApp (which I don't like at all) than an e-mail message sent from Mailgun to Hostgator. 

As a former hosting service provider, I've seen too many times messages being stuck on one end and taking ages to reach the recipient mailbox, because it was held on a "greeting delay" or "temporary rejection", or simply didn't arrive because the host was wrongly blacklisted.

What happens when you need to answer a message, try to log an app and it takes 55 seconds to a SMS (2FA) to get to your phone? I get mad, and I don't want my users to feel like this.

Passwords are unreliable as hell these days, because people are dumb, so I really love the idea and I think 2FA and passwordless logins are the future, but I'm not sure we can tell developers to trust e-mail, because people out there, which we cannot predict and control, are still using unreliable mail servers, because some admins are still trying to beat Google Mail by installing postfix (or exim) spamassassin, amavis, f-prot, razor, relying on dnsbl to filter spam, etc.

**Comment by barryvdh** [comment]
That could indeed be problematic. But passwordless login could be optional, eg. still allow users to use passwords if they prefer. But password resets suffer from the same problem, when using complicated passwords which users forget.

2FA doesn't have to use SMS per se, but can also use the Google Authenticator app (like your package), to generate codes.

And of course, you can still use the 'remember me' option, even when using passwordless login. And like some platforms, 2FA could only be required on the first signin on a new device.

**Comment by antonioribeiro** [comment]
Thinking about the many passwordless authentication options we have:

I developed Google2FA because I think 2FA via SMS is bad. And, to use a free HOTP/TOTP solution, your users just need a phone, tablet or a web browser (not very secure). Simple, reliable (?) and always present. As a second factor it's perfect, and I would like to have the courage to use it as the only factor. :)

For the first factor, what I think works the best (nowadays) is to send instant messages, it is also (kindo of) unreliable, because Telegram (or any other service) can be shut down (happened with WhatsApp twice here in Brazil), but it's faster than anything else and can be as omnipresent as e-mail.

I would also consider using Google2FA as first factor and, as a second factor, send a 6 digit random number by SMS **and** email (number on subject and link on body), if both fail (or get slow) at the same time it's just bad luck.

**Comment by Garbee** [comment]
As far as passwordless login goes, [SQRL](https://www.grc.com/sqrl/sqrl.htm) by Steve Gibson and his community working on it seems to be picking up some steam. It is still not finalized yet, so probably shouldn't have anything official done. But if someone from the community would want to hack out an easy package to use it to test with then that could be something. I believe there is already a Drupal implementation among a few other CMS systems in PHP, so they could be drawn from for implementation help.

**Comment by barryvdh** [comment]
I agree that 'passwordless login' (or SQRL) might be a bit experimental to standardize in Laravel, but imho the whole '2 factor login' could be simpler/default, even if it's just to remove some boilerplate and add it to the existing login methods. The TOTP tokens for Google Authenticator/Authy are pretty much used by everyone (Github/Google/Twitter/Facebook etc), so even if they're not 'the' solution yet, I guess it's the best yet ;)

@taylorotwell Is this something you're interested in. Should I start working on something for the core, perhaps based on flexible drivers for 2FA methods?

**Comment by barryvdh** [comment]
Perhaps this is already implemented in Laravel Spark in some flexible way, but I don't have access to that. So if so, let me know before I start working on it ;)

**Comment by barryvdh** [comment]
I've played with 2FA on a project. While the google2fa package works okay, there doesn't really seem to be any 'recommended integration' structure. Eg. where to hook in, how to store/configure methods or use recovery codes. So that leaves some benefit for this.

Rough idea, based on the Spark driver mentioned, and other Laravel auth stuff:

- Interface for 2FA methods (`enable($user, $data)`, `disable($user)`, `verify($user, $data)`)
- Multiple drivers possible via config. So a user could have multiple methods (eg. email/sms token, Google Authenticator token, Authy login).
- Recovery code could also be implemented as a method
- Simple table to store the methods (table with user id, method and array with config per user (google secret, authy phone etc), which determines which methods are enabled per user.
- View scaffolding per method for login page (show token form etc) and enable (show qr code or different form) and list of available methods (to change method or enable)
- Trait similar to ThrottlesLogin, which hooks into AuthController, to check if 2FA is needed and if so, redirects to 2FA page.
- Optional: middleware to protect only certain routes with 2FA. And/or use cookies to 'trust' computers, so 2FA is only asked the first time.

This way multiple drivers could be enabled if wanted (eg. use Google Authenticator by default, but allow email/sms or recovery code as a fallback alternative). But it does seem a bit complex like this, so a separate package could also work. Only problem would be hooking into the AuthController (although that might be fixed with login event listeners also)

**Comment by barryvdh** [comment]
FYI, this Digital Authentication Guideline: Public Preview from NIST: https://pages.nist.gov/800-63-3/sp800-63b.html drops SMS as a valid authentication method (because it's unreliable and can be spoofed).

It does allow OTP (one time passwords) passwords as 2nd factor (eg. besides password) and one-factor (primary login), as far as I understand. (But for level 2, at least 2 factors are needed)

Furthermore is suggest throttling (what Laravel already does) and a minimum of 8 char passwords (Laravel is default 6 now in auth scaffold?). Also max 30 days before re-authenticate.

**Comment by dakira** [comment]
As @taylorotwell asked us to vote on 5.4 features, I nominate this! ;)

**Comment by akalongman** [comment]
+1

**Comment by robinvalk** [comment]
I dont know if Webauthn was an option at the time but it's now recommended by W3C:
https://www.w3.org/TR/webauthn/

**Comment by taylorotwell** [comment]
Closing this due to some upcoming feature things that will resolve this.

**Comment by iAn-Pinto** [comment]
Has anyone come across a mobile number missed call based authentication implementation using Laravel or any other framework? I feel SMS OTP based 2FA and other methods like email etc are too cumbersome when my mobile app requires user to input an authenticated mobile number.
