### ISSUE TITLE
Propose: proper .env handling

### ISSUE THREAD

**Issue by owenson** [laravel/ideas#1111]
Most users expect .env to be authoritative, and not overridden by container envs in my view.

Consider changing Dotenv()->load() to Dotenv()->overload() because when using various plugins with docker, e.g. redis and elasticsearch, the hostnames are defined in .env, but docker defines a global environment variable ELASTICSEARCH_HOST or REDIS_HOST which is in an incompatible format.

Took me 3-4 hours to trace this bug down!

Or atleast make this more easily debuggable. Getting a dump from laravel saying csnt connect to http://elasticsearch:tcp://172.17.0.5. Is not very helpful for diagnosis.

I did have this problem about six months ago and i think ended up patching some other library as i couldn't work out the cause.

**Comment by sisve** [comment]
You're choice of words implies that because you didn't know how dotenv worked, you want to declare the current usage inproper and introduce a possible breaking change. The current behavior is already documented in a highlighted blue box at https://laravel.com/docs/5.6/configuration#environment-configuration

> Any variable in your .env file can be overridden by external environment variables such as server-level or system-level environment variables.

So, wouldn't the _proper_ way be for you to know what environment variables that your docker plugin sets and how it affects your application?
<br>
> Most users expect .env to be authoritative [...]

This goes against the documentation of dotenv and the linked documentetion for Laravel. Do you have a source for this claim?

**Comment by owenson** [comment]
My suggestion is simply to make it easier for your users, most of whom wont study or be interested in the minutiae of the framework.  Having explicitly defined vars overridden by environment variables (which I would consider far less important) was unexpected behaviour for me. And with docker it causes a difficult to debug error.  

Clearly you dont agree which is fine.

**Comment by concept-core** [comment]
Doesn't this just mean that you didn't configure you docker container correctly which leads to the error?

if so why not fix your container instead of wanted to burden everybody else with this change?

**Comment by MatthewSH** [comment]
How it works now is how it's intended to work. I believe @sisve and I actually had a discussion about this prior and I 100% agree with him on this. 

It wouldn't make sense to do it how you're proposing. Example of where that could fail is if I have multiple servers where say 1 is on Linux and the other is on a Windows server and they both share the same env (through something like Envoyer) then I wouldn't want this change because I want system variables to supersede the env file or else my application could break. 

I'm 100% against this change. :-1:

**Comment by owenson** [comment]
Hi

Ok well thanks for considering it anyway.  

The behaviour I experienced is the default for docker when linking other containers such as dbs.  Which then overrides the .env with a incompatible uri string for both elasticsearch and redis.

My only option to fix it is to patch the laravel code it seems, or use different names for my containers (e.g. not elasticsearch for my elasticsearch).

Maybe provide a note at the top of the .env file to alert users to the fact global environ will override.  And perhaps make an option to disable the behaviour.

**Comment by DrowningElysium** [comment]
Another fix is changing the variable name in your env file to something else and of course changing the env() helper call in your config files
