### ISSUE TITLE
[Proposal] Update the design of the list of commands in Artisan

### ISSUE THREAD

**Issue by nunomaduro** [laravel/ideas#1148]
Hey 👋

This proposal addresses **modifications on the output of the artisan list command**.

Currently, if you type `php artisan` the terminal will output this:

![screenshot 2018-05-01 18 20 40](https://user-images.githubusercontent.com/5457236/39481771-d68fe5b0-4d6c-11e8-837f-1efe292cb705.png)

**The idea**: Perform minor modifications on the point 1 and point 2. Remove entirely the point 3 and remove subtitles ( the yellow text) from the point 4.

The end result will be:

![example-2](https://user-images.githubusercontent.com/5457236/39481843-166be8be-4d6d-11e8-9bfd-5e0e28be5442.png)

You can install the package [Laravel Console Summary](https://github.com/nunomaduro/laravel-console-summary) to see the end result locally in your machine. But I thought to perform a PR to the core with this exact same code instead of proposing the addition of a package.

What do you think about this idea? 🤔

**Comment by AkenRoberts** [comment]
Hey Nuno! Thank you for another contribution. 👏 

Can you explain _why_ you think these changes are an improvement? What's the reasoning / rationale?

The output formatting comes unchanged from the Symfony Console component, so any modifications would need to be added to the Laravel core and become another item to maintain. That reason alone dissuades me from wanting to touch formatting without good reason.

**Comment by nunomaduro** [comment]
@AkenRoberts Thank you for your reply!

Is all about giving relevance about what truly matters: **The commands**.

Nobody cares about the available options, and there is always the `help` command to see available options. And those options **could confuse a newcomer** on the framework.

The implementation would be something similar to this: https://github.com/nunomaduro/framework/commit/af8a0e30853fa6e654d3d8d9619ae2174ceded75

**Comment by sisve** [comment]
Using the terminal confuses a newcomer. Installing virtualbox, vagrant, sshing and virtual machines confuses a newcomer. Valet and dns masquerading confuses a newcomer. The default way people configure their xampp configurations with laravel in subdirectories, which isn't supported, confuses a newcomer.

Are we really sure that the output from `php artisan` is the place to start when clearing up confusing things?

**Comment by divdax** [comment]
It's ok but not really needed.

**Comment by brunogaspar** [comment]
Hey @nunomaduro 

> Nobody cares about the available options

Meh, it's your opinion because you already know these :), newcomers don't, nor they are really documented, as far as i know. Yeah i know, you can type `artisan help` but it's not entirely the same if you look at it.

I find the current way totally fine, which is, as stated by @AkenRoberts , Symfony default way of outputing and the default way for tools like Composer pretty much.

Why should we diverge from this for the sake of making it "pretty"?

I would honestly prefer to see improvements being done on commands like `route:list` which is a terrible mess on 15" screens over this type of changes.

Just my opinion ✌️

**Comment by 36864** [comment]
If the point is to make `php artisan` stop showing usage information, I do not think that's a good idea. An argument could be made in the opposite direction, where the default would be to only show usage info, or show usage info along with a restricted list of commands (possibly all the non-namespaced default commands?), instead of just calling the list command.

If the point is only to change the way `php artisan list` works, abbreviating the usage information on that command could be reasonable, but I think removing it entirely would be a mistake. I don't find the current output to be in any way confusing or overwhelming. In fact, I found it quite useful as a beginner, as it saved me quite a few calls to the `help` command.

As a final note, I really dislike the idea of removing the namespace separators. I just don't see how that can be an improvement in any way.

**Comment by nunomaduro** [comment]
After proposing a PR into the core, the PR got closed. 👍

**Comment by mfn** [comment]
I did like the proposal (based on the screenshots), but I understand the counter arguments.

In practice I never see the top (1., 2. and 3.) because in big projects the number of commands exceeds the regular terminal size already.

I'm more annoyed that, when you provide a multiline-description (and some commands simple need more expressive ways…), there's no "line break" algorithm or logic going and it becomes a mess.

I would love to have the ability to define a command with a "singe-line brief description" which gets shown in `./artisan`, like this:
``
  what:ever:command           One-liner brief description
```
