### ISSUE TITLE
Laravel migration consuming too much time 

### ISSUE THREAD

**Issue by Sarmad007** [laravel/ideas#1180]
I'm using laravel 5.6.The issue i'm facing occurs during migrating a  db.It takes too much time i.e 20 minutes.
I'm using mariaDB.

**Comment by tomschlick** [comment]
That would be a problem with the queries you are running in your migrations, not the migration system itself. For example, we have hundreds of migrations at work and they run in just a few seconds.

**Comment by Sarmad007** [comment]
No,Issue with the queries at all,as i have tested on another pc

**Comment by LKDevelopment** [comment]
Than it is possible an issue between the host where you start the migrations and the mariadb server? We have the same setup with ~500 Migrations and it works in under 10 seconds..

**Comment by mbitokhov** [comment]
The only reason why it'll take 20 minutes to migrate is if you have hundreds of millions of rows. If you add an extra column of a type char(255), you're gonna have to free 255 bytes for each row, meaning you just added a gigabyte for every 4 million rows

It takes time to free up all that data. On a testing environment, you shouldn't have that much (unless you were playing around with live data)

I tell that to my coworkers all the time, but they insist on pressing Ctrl+c, screwing up their database, and then coming to me to fix it

**Comment by Sarmad007** [comment]
@mbitokhov Well my database isn't that heavy.It takes 2minutes for 5 migrations.And i think thats too bad.

**Comment by sisve** [comment]
Instead of vague "my car takes 20 minutes to go to the store", how about giving us some actual details to help you debug the issue? Clearly your experience isn't shared with everyone, and maybe it depends on the car, the roads, and how far away the store is.

You've already said that this is not a general problem. You say that "they are working normal on other pc". This clearly indicates that there's a problem on one specific machine that you are using.

This sounds like a attempt to get support. The idea isn't "make them fast", because they are already fast. There's no new idea presented in this issue. Close this issue and start asking on our forums, Slack or other area that is focused on what this is; a request to help debug a speed issue on a machine.

**Comment by Sarmad007** [comment]
@sisve Closed!!

**Comment by sangrialdrete** [comment]
@Sarmad007 did you solve this ? I have the exact same problem, not many migrations, not many data, runs fine with other developers, it takes arount 20~30 minutes to migrate and seed. I resintalled mysql and nothing, I even switched to docker and Im facing the same issue. If you can tell me how you solved this I would appreciate it.
