### ISSUE TITLE
Update array of artisan `inspire` quotes to feature more women and people of color

### ISSUE THREAD

**Issue by nikhiltri** [laravel/ideas#1186]
Considering all the conversations happening in the world today about representation, I wonder if anyone would have any objections to me submitting a pull request to update the array of quotes used for the artisan `inspire` command to include more women and people of color?

The current quotes seem to be centered around simplicity and quality, so I’d find quotes that stay on that theme. 

Let me know!

**Comment by sisve** [comment]
Laravel is an open source project and you need to approach it as such. Just send a PR with whatever changes you want. By approaching this as something that needs a collective agreement you imply that there is a backside to your changes, or that you're not sure you're doing the right thing. If you're unsure how to contribute to the project, use the [forums ](https://laracasts.com/discuss) or [Slack](https://larachat.slack.com/).

**Comment by mallardduck** [comment]
So I really liked this idea and wanted to contribute to this. I may have been a bit loose with my interpretation of the theme, but the change can always be revised. Check it out here: laravel/framework/pull/24353

**Comment by mattstauffer** [comment]
Just because I think this is an important distinction: I think asking in this context was totally fine. That’s the entire purpose of ideas: to run ideas by other people, especially if it can be seen by Taylor or someone else with decision making power, or someone who knows the history of such conversations, etc. 

It is an open source project; but I think @nikhil has read correctly that that doesn’t mean it’s  wise to prompt conversations like this before submitting the code. 

TL;DR: imho, this was a good use of the “ideas” project and doesn’t merit chiding. 😬😘

**Comment by mallardduck** [comment]
@mattstauffer I agree and like your philosophy. I think you and @sisve nailed it there.
Based on the comment my PR got though, it seems like people can always find a reason to question it.

**Comment by nikhiltri** [comment]
Hey all,

Yes, I brought up the question in "ideas" because I wasn't sure if there was any history behind the creation of the `inspire` command that I should be cognizant of before I submitted a PR to change it. Thanks for encouraging a space for dialogue about it, @mattstauffer. I recognize this question goes a little outside of the core functionality and behavior of Laravel, but I submitted it for a few reasons:

- I haven't yet contributed any code to Laravel and thought this might be an easy one for me to get my toes wet in the codebase and engaging the community
- As much as we may feel uncomfortable getting into political discourse in the development of the project, this list of quotes already makes a political statement. A list like this notes where the project finds inspiration, and that is largely composed of quotes by white men indicates to me how much room there is for myself as a person of color in the project. And I presume a similar reading can be had by women, trans people, people with disabilities, and people from other marginalized communities who are constantly gauging our safety in a space. There are subtle ways a community can communicate who is and isn't welcome, however unconscious the intention might be. As this command is often used as a first impression of to the Laravel CLI, I'd like to take it as an opportunity to communicate who the project thinks about when it thinks about its community. 
- I bring no judgment to the people who wrote the initial list, nor am I trying to make a hard connection between this list and any level of intentional exclusion that might exist in the Laravel community. My experience thus far has been warm and welcoming to everyone I've talked to about Laravel, which is why I feel safe enough to be vulnerable and raise this honest question.
- Any list that comes out of this conversation doesn't have to be perfect. I'd like whoever is interested to take one small step at updating the list so that future contributors can see this list isn't set in stone. That maybe it can be seen as a reflection of the Laravel community at any given moment in time and is in as much flux as the community itself is.

Those are my thoughts for now. I've been going through some of my reading notes over the past few years, and I'll plan to follow up with a list of quote ideas that we can discuss further, and I'll bundle in  @mallardduck's list with what I follow up with.

Thanks!
nikhil

**Comment by 36864** [comment]
I believe you're giving way too much attention, or attributing too much importance to what is a simple example command of no consequence.

Generally, I'm against changes that are made just for the sake of change, or additions that don't actually add anything of value.
That said, additions to the inspire command are not unheard of, and as long as you keep them within the general theme, I don't see a strong reason not to add them. 

I do, however, have a problem with your reason for adding them. It's very hard not to read your reasoning as "I find these inspirational quotes insufficient because they're mostly attributed to people of a specific sex and skin color, so I'm adding quotes from these other people specifically because of their skin color or sex". If the current list featured very few quotes by white males, would we still be having this discussion? Would anyone have cared at all?

> [...] A list like this notes where the project finds inspiration, and that is largely composed of quotes by white men indicates to me how much room there is for myself as a person of color in the project [...]

This is, in my opinion, a reflection on your own limitations and biases rather than a problem with the framework. The fact that you want to define your place in the world based on the physical attributes of some people who said some stuff that the creators of a framework found inspirational. 


Before deciding on what quotes you're going to add, strip them of authorship. Consider the quotes for what was said, not who the person was or what they looked like. Consider if those quotes belong in this command, in this context, and if they fit the existing theme. 
As an example, the recent PR had a specific quote by Queen Victoria:
>'The important thing is not what they think of me, but what I think of them. - Queen Victoria'

Is this the kind of quote you consider inspiring? Does it even make sense in the context of a framework designed to help developers build websites for other people to use? Would it make sense if your neighbor had said it, rather than a queen, whose authority was absolute and whose opinion objectively mattered more than any other?

Stealing another quote from that same PR:
>'Be less curious about people and more curious about ideas. - Marie Curie'
I'd say this applies to quotes as well.

**Comment by taylorotwell** [comment]
Anyone is free to submit quotes at anytime. Laravel is open source. 👍

**Comment by 36864** [comment]
@mallardduck I only objected to the first quote, and only in the context of a web development framework. When you're creating a website, you want other people to use it. You want people to like it. What you think of your clients matters far less than what your clients think of you (or your work) in this context.

I have no objections to the second quote, I used it to support my reasoning for choosing quotes based on what is said rather than who said it.

**Comment by nikhiltri** [comment]
Hey all,

Here are a few ideas, including the ones in @mallardduck's pull request:

```
'Change requires intent and effort. It really is that simple.' - Roxane Gay

'Whenever you are creating beauty around you, you are restoring your own soul.' - Alice Walker

'You have to act as if it were possible to radically transform the world. And you have to do it all the time.' - Angela Y. Davis

'What is important is not any particular idea but the process of continuing development, as the contradictions or limitations inherent in any idea surface and require the leap to a new idea.' - Grace Lee Boggs

'When times are hard, do something. If it works, do it some more. If it does not work, do something else. But keep going.' - Audre Lorde

'"Beauty does not need a reason," Okwu responded.' - Nnedi Okorafor

'I dream. Sometimes I think that's the only right thing to do.' - Haruki Murakami

'What could not be changed must be borne. And since nothing could be changed, everything had to be borne.' - Monica Ali

'The important thing is not what they think of me, but what I think of them. - Queen Victoria',

'Let us make our future now, and let us make our dreams tomorrow\'s reality. - Malala Yousafzai',

'Done is better than perfect. - Sheryl Sandberg',

'Be less curious about people and more curious about ideas. - Marie Curie',
```

**Comment by nikhiltri** [comment]
And one more:

> “Dreams and reality are opposites. Action synthesizes them.” —Assata Shakur
