### ISSUE TITLE
[6.0] [Proposal] Transforming Laravel MVC pattern similar to VueJS template architecture.

### ISSUE THREAD

**Issue by Modelizer** [laravel/ideas#1198]
Note: This is just an Idea but it is derive from experiencing issues of putting things here and there and making route files 1000s of line.

```html
<!-- users.lara file -->

use App\Requests\UserRequest as Request;
use App\Role;
use App\User;

<route name="user.lists" url="/users/{role}" middleware="auth"></route>

<method request="userRequest" role="role">
    return User::whereRole($role)->limit($userRequest->get('limit', 10))->get();
</method>

<blade>
    @extend('layout.dashboard')

    <table>
        @foreach($users as $user)
            <td>{!! $user->name !!}</td>
        @endforeach
    </table>
</blade>
```

- `method` will process the request.
- Whatever is been returned from the method will be pass to blade.
- In method, parameters will be treated as html attributes.
- It is not necessary that routes should be in `user.lara` file it can be treated separately.
- We already have functionality of listing all routes but addition to this we can provide which template is register or corresponding to which route.

Advantages:
1. This is much more compact and readable.
2. No need to hiphop multiple files.
3. One file and job done.

There is lot of space for improvement and can be made more cleaner? I'm not sure but open for feedback and would be great if this sound valuable to community. Thankx.

**Comment by sisve** [comment]
This would basically remove the separation between the layers in an MVC application. One large file with both code-behind logic and ui-logic? Couldn't we just port WebForms to php?

**Comment by Modelizer** [comment]
`method` is an entry point of the given route and the logic can be put into Jobs or any other design pattern which fits the desire need. Also the redundancy in blade can be divided into components. There are lot of things which we can do to keep this file small. Regarding webforms, it can be a separate package but I don't see it suffice the current need. 🤔

**Comment by jenky** [comment]
How about no? Are you going to write the transpiler/loaders for your `.lara` file?

**Comment by Modelizer** [comment]
Yes. It would be similar to blade compiler.


- Mohammed Mudassir On Mon, Jun 04, 2018 at 7:19am, Lynh < notifications@github.com [notifications@github.com] > wrote:
How about no? Are you going to write the transpiler/loaders for your .lara file?

**Comment by jenky** [comment]
No, it's not. Anyway, call me if you have something with your **compiler**, maybe?

**Comment by Modelizer** [comment]
If you are treating `.lara` as a language then yes it would be a good Idea to go with transpiler. So that we can add multiple support for other packages as well. Example if I want to add support for twig then I can do it easily and only need to use `<twig>` tag. But I'm not sure here weather community will use it or not? But I feel hire rate of success.

**Comment by sisve** [comment]
You present a problem of route files with thousand of lines, but your suggestion suggests that the routes doesn't have to be in the new file. Isn't your suggestion just spreading out those thousands or route lines over thousands of views?

Why should this be part of the framework, and not provided as a third-party package?

> This is much more compact and readable.

Compact, yes. Readable, no. It's perhaps easier to get an overview of the view you have open, but finding the proper view when you've spread out the routes over several files? I doubt it. Also, the syntax highlighting, the static code analysis tools, etc. There will be no tooling available for this new view format.

> No need to hiphop multiple files.

This can be accomplished by writing your entire application logic in one big file. But is this really a problem; I believe most editors have keyboard shortcuts to open files, and some even have the tooling to navigate from a controller to a view directly.

> One file and job done.

I believe this is just repeating the previous argument.

Have you considered trying to implement this view engine as a third-party package? That way people can opt-in and try it out, and if people start using it in large numbers, perhaps it will be included in the framework.

**Comment by jenky** [comment]
Let's say I have `<blade>` `<twig>` `<smarty>` `<plates>`.... in one file, which one is your compiler gonna pick? Even if you change the snippet like Vue (`<template lang="blade"></template>`), do you think the community will write the extra loader for their packages? In `javarscript` world, you have to transpile `ES6` to `ES5` in order to run in the browser, that's why Vue SFP concept works very well. But in `php` which benefits does I get if I run my code through a `compiler/transpiler` just to make it works

- Performance: I guess not
- Reuseable: Doubt
- Readable: For me. Nope
- Learning curves: You tell me 
- Working experience: I'm working with L5 now, but my future project uses `Symfony` or `Zend`. Haha, good luck

Sorry, I'm not felling your **high rate of success**

**Comment by Modelizer** [comment]
I can answer all of the question but I feel these question can be answer from yourself if you think what answer should be but still I'll answer few of them.

@sisve it will not be a big file. As I said, it can be delegate any other file depending on the complexity.

> Isn't your suggestion just spreading out those thousands or route lines over thousands of views?

I assume people will get the point but I need to be more explicit here. If we have 1000s routes then probability will have 1000s of methods (and most of them are not big and complex but do the job of routing to another class and get the result) and these method call 1 view file. So the segregation file is too much which can be push to one file. If it still get too large then developer should consider refactor.

> Why should this be part of the framework, and not provided as a third-party package?

This is solving a problem by not putting things here and there. This would be new way of using Laravel as a template and I'm not sure did any other framework try to do this way. If its still get rejected to be a part of 6.0 then there is I'll try to make this as a package.

@jenky do you use both template at same time?

I'm sure answer would be no. And most of the people don't do it because it is hard to maintain.

> Performance

Caching

> Readable

Do you want it should be written in plan english?

> learning curve

Not too long, but yes it has small amount. Every new implementation has its own learning curve.

**Comment by sisve** [comment]
I think the approach is all wrong. There's clearly a lot of specification that needs to be written, and weirdness that needs to be worked out. That will only be done when you start coding and find the weird stuff. At least write a proof-of-concept as a separate package, and then lobby to include that into the framework.

Don't wait for us to fully evaluate your idea and turn it down before writing it yourself. It just sounds like you do not want to write it at all.

**Comment by jenky** [comment]
> @jenky do you use both template at same time?
> I'm sure answer would be no. And most of the people don't do it because it is hard to maintain.

Then I'm pretty sure that most of the people don't have 1000s routes. 

Well, if you think it's good, then like @sisve said create your own package. Why do you have to wait? It might be part of the core if you can draw attention from community.

**Comment by 36864** [comment]
In your example, you called the file `users.lara`.
Does that mean you'd have one file per resource? If so, do you define all the views for that resource in the same file?

If not, let's assume that you actually meant to call it `users.list.lara`
Now you also have `users.show.lara`, `users.create.lara`, `users.edit.lara`
Where do you define the `store` and `update` routes? In new `.lara` files? These would (hopefully) not have any view data associated with them. Until this point, I assumed all these files would be in the `views` folder, and all the logic would still be abstracted away to a controller, ideally with a `<controller>` tag instead of the `<method>` tag (basically controller routes vs closure routes).

Further, where do you define redirect routes? If I want `/user/{role}` to redirect to `/users/{role}`, do I add that route to the `users.list.lara` file or make a new file entirely?

As a side note, why are you printing the user's name without escaping it in your example? That just sounds like a really bad idea.

**Comment by martinbean** [comment]
> This is just an Idea but it is derive [sic] from experiencing issues of putting things here and there

That’s called _organisation_. Laravel has conventions, so I know when dealing with a Laravel app I’m bound to find console commands in a *app/Console/Commands* directory, controllers in *app/Http/Controllers*, queue jobs in *app/Jobs*, and so on.

> making route files 1000s of line [sic].

You _can_ split routes into separate files if you really do have that many. But I’ve never worked on a Laravel app with “thousands” of routes, and I’ve been working on Laravel projects of various sizes since 2013-ish.

**Comment by Modelizer** [comment]
@36864 every single request will have its own file.If you put one thing in one file then it would be hard to understand which route is attach to which method and so on.

> Further, where do you define redirect routes?

Itself in the method. As I said above even if there is no `<blade>` there will be a file to process and redirect it as required.

@martinbean Thank you for letting me that it is called "organisation". You enlighten me. 

Organising is not always about splitting things. It is about how it can help you to easily access it. Both approach has there own flaws and advantage. I'm not saying this proposal consist of everything but if you have some concrete discussion which can help to make this methodology better I'm open to here it.

> You can split routes into separate files

We already did and it is not totally about splitting. There should be balance segregating code into multiple files. And the balance come by looking at what scale my current approach is getting redundant. Splitting extensively end up adding one more layer of complexity to know which routes belongs to which file.

Whoever is reading this should know that this is just a proposal which needs more furnishing. And this is not 100% right way. Although if we start focusing on advantage and solve the disadvantage would make this communication more healthier.

**Comment by AkenRoberts** [comment]
@Modelizer Disagreements and negative comments aside, kudos for a unique idea that creates an interesting discussion. 👏

**Comment by wimurk** [comment]
Please stop. Just stop

**Comment by Modelizer** [comment]
@wimurk please unsubscribe the thread.

@AkenRoberts Thankx!

As I see people are embasising on Cache and route. So the better way would be totally remove html and dealing this into raw PHP manner. Regarding route as I said earliear route is opetional and dependent on user. If they want to put into routes/web.php file then they are open to do it but they only need to replace controller name with `.lara` file.

@36864 when its start redundancy then we extract it into a common file which is `@include`. Also, I don't care anymore about MVC because it is out dated and build for small and intermediate project. I believe to organise my code using Domain Driven Design.

Things I miss in the community is that we are not solution oriented; in fact we are not able to see the potential in the Idea rather find flaws and not able to understand the use case. Before asking me question you ask yourself what will be solution and propose it here how we can do it! Then still if you think there is no potential then ignore.

@sisve I'm sorry I miss one of your important comment. As you said to propose a proof of concept (A separate package) which I will do soon but before that I want to furnish this Idea more by taking some of the feedback and what can be done better which I figured out. Thankx!

**Comment by sisve** [comment]
> Also, I don't care anymore about MVC because it is out dated and build for small and intermediate project. I believe to organise my code using Domain Driven Design.

Those are two totally different things, and do not exclude each other. I use MVC _and_ domain-driven design. Your statement doesn't build credibility for your idea.

> Things I miss in the community is that we are not solution oriented, in fact we are not able to see the potential in the Idea rather find flaws and not able to understand the use case.

You've presented an idea that very few agrees is a good idea. Don't accuse us of not being solution oriented. We disagree with your idea, and we've told you to implement it yourself as a third-party package and show that it actually works. Do you expect us to jump on to this and spend _our_ time on it?

> Before asking me question you ask yourself what will be solution and propose it here how we can do it! [...] Then still if you think there is no potential then ignore.

No, that is not how discussions works. You need to hear and see the disagreements. And there's no requirement from our end to give you solutions. It's usually constructive when both parties want to go forward to come with solutions, or when there's a goal that is in everyones interest to reach. However, you've not presented a goal here. In fact, you've written ...

> As I see people are emphasising on Cache and route. So the better way would be totally remove html and dealing this into raw PHP manner.

... which is a weird goal. You want to stop people focusing on caching and routing, two very common things in web applications? And even if their focus was a problem, you present a solution that we do not agree with. Either because we think it's a bad solution, or because we do not see the problem to begin with. We cannot be solution-focused when we don't see the problem.

Consider the following statements, and what would happen if everyone that disagreed was quiet.

* Surströmming is the best thing ever.
* Every pizza should have pineapple on it.
* Tuna and ice-cream is a good combination.

There will be disagreements on this. You're welcome to try any of these delicacies, but if you open up a restaurant focusing on them, wouldn't you want to know that a majority of the people around you disagrees?

Related surströmming videos:
1. https://www.youtube.com/watch?v=_haw_YDC_zo
2. https://www.youtube.com/watch?v=e-qflm0APTk

**Comment by 36864** [comment]
@Modelizer 
>Things I miss in the community is that we are not solution oriented

Pretty much every question I've asked you has been to try and understand how the solution would work. I'm imagining that this system exists, and considering what that means for my workflow. How do I use this? Is it better than my current workflow? 

>we are not able to see the potential in the Idea rather find flaws 

The changes you are proposing are vast and have severe technical implications that _MUST_ be sorted out before we even try to go ahead with this. What you call finding flaws I call hammering out project requirements and implementation details.

>If they want to put into routes/web.php file then they are open to do it but they only need to replace controller name with .lara file.

This would solve the "How would laravel know where the routes are?" problem, but then one of the assumed advantages of this system (or maybe the sole purpose of it), which was to not have a routes file to begin with, disappears.

>As I see people are emphasising on Cache and route. So the better way would be totally remove html and dealing this into raw PHP manner.

I don't actually understand what this means. Please clarify. If you get rid of all the html in your project, you're left with an API service. Which brings me to another point, which is how do you define an API endpoint in this new system? The syntax you've showed implies that the `<method>`, or the controller code of your route, only serves as a view composer, passing data to the `<blade>` block. In an API route, it usually makes no sense to even include a view to respond with, so what are your ideas regarding API routes?

>Also, I don't care anymore about MVC because it is out dated and build for small and intermediate project.

I think this touches on one of the reasons I am not able to see this system working. I could see it working in small-scale applications, where you have maybe a couple dozen files and they each load their own data, and each have their own view, and they might be simple enough that you don't need all the abstractions of controllers, view composers, etc. . But in large projects? 
All this would do is add another file in the file stack for each route. You'd still have your controller code abstracted away. You'd still have layout view files, partials, etc. to deal with. You'd probably still have view composers to go with those. As we've established earlier, you'd also still have a routes file that points to the file where the route is handled.



Moving on to a new topic here, and a thing that I glossed over initially, you're proposing that controllers no longer return views, but instead behave as view composers, as evidenced by your example. Currently, I can have separate routes return the same view with different data quite easily, even reusing the same controller method if I were so inclined (by deciding what data to load depending on route parameters, for example)
If I have a view, say `posts.index`, which displays a lit of posts, and I want to have two routes `posts/latest` and `posts/mine` which, respectively, load either the latest posts or the calling user's posts and displays them through the `posts.index` file, how would I express that in this new system?
