### ISSUE TITLE
Support for row expiration date

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/ideas#1205]
Maybe (when we insert the row in the first place) we what to set a timestamp in future for the row to be considered as a soft deleted row, .
Just like redis auto expires it's keys after a period of time.

```php
namespace Illuminate\Database\Eloquent;

class SoftDeletingScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        $builder->whereNull($model->getQualifiedDeletedAtColumn());
    }

...
```
Currently it assumes that the timestamp is in the past and only checks for null

**Comment by 36864** [comment]
You can extend the trait, override the apply method, and use your extended trait in your models to get the desired functionality.

I think this has been suggested in the past, and the general consensus was that it wasn't a very common use case, so the added complexity wasn't worth bringing it into the core.

Maybe, instead of taking advantage of the soft delete scope, we could add a new "expires" scope. Semantically, having separate "deleted_at" and "expired_at" columns could make sense to determine if a model was explicitly deleted or simply expired.

**Comment by imanghafoori1** [comment]
@36864 Thanks
I guessed it, Closing on duplication.
