### ISSUE TITLE
PHP extension for preloading framework classes for php-fpm child process

### ISSUE THREAD

**Issue by amerov** [laravel/ideas#1248]
PHP core discussion: https://externals.io/message/102052
PHP frameworks boot time is very cost.
I think PHP frameworks core teams should be more collaborate with PHP core.

**Comment by sisve** [comment]
That is a two month old mail thread talking about something that the php fpm does not yet have support for.

What do you want us to do? Do you have a checklist or any clear criteria for when this issue is done and can be closed? It currently comes across, to me, like you want to chat about something. There are better places to have that chat than the ideas repository.
