### ISSUE TITLE
Using phpspec/prophecy instead of mockery/mockery ?

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/ideas#1262]
As you can see, PHPunit has already a `phpspec/prophecy` dependency out of the box.

Why not using it instead of `mockery/mockery` ?

Official PHPUnit documentation: https://phpunit.readthedocs.io/en/7.1/test-doubles.html#prophecy

**Comment by sisve** [comment]
Because we're already using mockery.

We already have tutorials for mockery. We already have guides for mockery. We already have blog posts, questions and answers, and a shitload of other community engagement that uses mockery.

Instead of asking why we aren't using a particular library, tell us why the current choice of library is bad and how it cannot be fixed. Tell us why we should throw away time put into existing documentation to use a new library.

**Comment by sevillaarvin** [comment]
Hi @arcanedev-maroc I have the same question as you. I have no opinion on whether prophecy or mockery should be used for testing, but I read this blog which may help clarify the difference between the two, though I barely understand it myself.

[https://everzet.com/post/72910908762/conceptual-difference-between-mockery-and-prophecy](https://everzet.com/post/72910908762/conceptual-difference-between-mockery-and-prophecy)

**Comment by arcanedev-maroc** [comment]
The article you posted highlight two concepts: **structure binding** & **message binding**

**Mockery** uses approach called **structure binding** - it means your test is now bound to the way your code is structured

**Prophecy** uses approach called **message binding** - it means that behavior of the method does not change over time, but rather is changed by the other method.

> **Conclusion:** So the core conceptual difference is not in how you write tests, but when you fix them. Mockery sometimes could put you into the situation, where you would write tests that will inevitably fail because of the private structural refactoring. Where’s Prophecy postulates that there is no failure in this case - because the actual behavior stayed the same.
