### ISSUE TITLE
[Proposal] Simple and Organized Accessors & Mutators

### ISSUE THREAD

**Issue by sr2ds** [laravel/ideas#1270]
Today we insert Mutators and Accessors directly on Model files.

Problem: Biggest Model File and confusion with relationship comum methods.
Proposal Solution: Model automagic discover separeted files, see:

Model: PurchaseOrder
Mutator: PurchaseOrderMutator
Accessor: PurchaseOrderAccessor

PurchaseOrder Auto discover yours complements files.

**Comment by mfn** [comment]
You didn't state _why_ it should "automagic" discover something, what would the benefit of it be?

But if, for the sake of organizing your source code, you don't want to "physically" pollute your models, you can always use traits to put them someplace else.

**Comment by 36864** [comment]
What you're describing is a system for implicitly adding traits to a class instead of declaring their usage explicitly. This would likely have an impact on performance and require quite a bit of custom code as I'm fairly sure there's no autoload mechanism for that.

Just use traits. Make your new accessor/mutator traits and declare their usage in the model. You can even reuse generic accessors instead of having to make new files for each model.

**Comment by topclaudy** [comment]
You might be interested in https://github.com/topclaudy/eloquent-mutators
