### ISSUE TITLE
[Internals] Process for backporting all bug fixes to LTS version

### ISSUE THREAD

**Issue by staudenmeir** [laravel/ideas#1284]
Laravel promises two years of bug fix support for the LTS version. But in reality, only a few of the merged bug fixes get backported. It mainly happens when people explicitly ask for them.

I think that the LTS version should receive all bug fixes. It's a waste of time and resources if users on 5.5 (LTS) have to debug issues that have already been fixed on 5.6.

Who would be responsible for that? The contributor who submitted the PR? The maintainers? A dedicated "backporter"?

**Comment by tomschlick** [comment]
I think mostly Taylor would be responsible for that now. He has a lot on his plate though so that's probably why most of the things that are back-ported are security related or things commonly requested.

That being said I dont think he would mind if you submitted PRs to backport stuff to LTS versions. Those are easy wins so long as they dont cause regressions.
