### ISSUE TITLE
[Proposal] A configuration in logging.php to decide how deep to show stack trace in logs

### ISSUE THREAD

**Issue by alimranahmed** [laravel/ideas#1285]
**Currently**
if an exception thrown, we see hundreds of lines containing the stack trace of that exception which is useful sometimes. But most of the time only the exception message is enough debug or we might just need the top most lines of the stack trace to know what actually happening.

**Proposal**
Won't it be useful to have a configuration somewhere in the logging.php to decide how deep we want to show the stack trace. If the value is set to 0 then it won't show any stack trace but only the exception message.

**Comment by mfn** [comment]
I would be surprised if this isn't already possible.

The logging infrastructure uses monolog and the property `exception`. Did you give it a try configuring the formatter in a way not exposing the exception?

Also: first thought I have: you want to use custom logging e.g. via the Facade like `\Log::debug` instead of exceptions, so maybe rethink your architecture.
