### ISSUE TITLE
[Question] Why is calling whereNotNull in HasOneOrMany#addConstraints.

### ISSUE THREAD

**Issue by hrs-o** [laravel/ideas#1341]
When I look at queries generated using hasMany, `whereNotNull` feels redundant.
Is not it better to remove the call of `$this->query->whereNotNull($this->foreignKey);`?

[/Illuminate/Database/Eloquent/Relations/HasOneOrMany](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L72)

```php
    public function addConstraints()
    {
        if (static::$constraints) {
            $this->query->where($this->foreignKey, '=', $this->getParentKey());
            $this->query->whereNotNull($this->foreignKey);
        }
    }
```

## Example of a query generated by hasMany.
e.g.) $this->hasMany(~~~)->toSql()

```sql
select * from `example` where `example`.`id` = '1' and `example`.`id` is not null;
```

## Examples of queries I want.

```sql
select * from `example` where `example`.`id` = '1';
```

I do not need `column not null` if the condition is` column = value`.

If this call is necessary, I would be happy if you let me know if there is any function that I do not anticipate.

thank you.

---

This sentence was translated by google.
https://translate.google.com/

**Comment by staudenmeir** [comment]
Yes, it is necessary: https://github.com/laravel/framework/pull/8033

**Comment by hrs-o** [comment]
I understand. Thank you very much.

**Comment by serpentblade** [comment]
Sorry to dredge this up 18 months later, but I've had this same exact question for a long time.  I realize this is closed, but I'd be curious if a better solution could not have been explored.  It feels like bugfix was too heavy handed a solution for the corner-case it was solving.

It seems the real underlying issue is that when `getParentKey()` is `NULL`, this line:
```
$this->query->where($this->foreignKey, '=', $this->getParentKey());
```
gets smartly re-written to be the equivalent of:
```
$this->query->whereNull($this->foreignKey);
```

This causes the problem addressed in that original bug ticket/PR.

Adding the line `$this->query->whereNotNull($this->foreignKey);` fixes the symptoms of the problem, but it feels like more of a patch to the corner-case that has the downside of adding an extra unnecessary where clause to 99% of other queries.

I feel it may be more prudent to only apply this not null check in the rare case where `parentKey()` happens to be NULL (which seems to be on newly created objects).  Thus resolving the actual issue, and cleaning up a lot of queries that don't need that additional `is not null` check.


Something as simple as wrapping that line in a `is_null` check feels like it would be the better solution:
```
if (static::$constraints) {
    $parentKey = $this->getParentKey();
    $this->query->where($this->foreignKey, '=', $parentKey);

    if (is_null($parentKey)) {
    	$this->query->whereNotNull($this->foreignKey);
	}
}
```

Although there is likely something more eloquent than that (pun intended)

**Comment by grafhax** [comment]
100% agree with @serpentblade
