### ISSUE TITLE
View cache 'flatten' files

### ISSUE THREAD

**Issue by danilopinotti** [laravel/ideas#1400]
According to some searches, when there are many nested views (extends, includes, etc), the projects tends to lose performance.

My suggestion would be to include in the '**view: cache**' command, the '**--flatten**' option, which causes all 'nested' views to be included in a single file.

Some references:
https://medium.com/swlh/laravel-speed-booster-6babd07d84ab
https://github.com/Te-cho/compile-blades

**Comment by sisve** [comment]
I havn't looked into the source, just a quick glance at the documentation.

There are some complex points;

- Recursive views (views including themselves). Commonly used to render tree structures.
- Inner views are currently executed in a separate context from the parent view. We want to keep this, an inner view should not be able to overwrite parent variables or behave differently from non-flattened views.

The linked project looks like being on the first iteration, there are still some things commented as pending and in-progress, there are no tests, and the links to demonstration or profiler details aren't working.

The linked article is all over the place. The mention of the Renderable check in `View::gatherData()` doesn't make sense to me at first glance. Is he saying that the mere check if a parameter is Renderable is the problem? Is it just the iteration that is slow? And if so, how much time is php spending on a foreach?

I think we need to figure out where the problem is. Is it code execution, or file system access? The file system (and parsing) will probably be better with PHP 7.4's [preload functionality](https://wiki.php.net/rfc/preload), but it wouldn't speed up the code execution.

Just adding code files together will run into problems. I believe Amazon once ran into problems in their javascript minification when they concatenated scripts together, and one of them happened to enable strict mode. Any non-strict code that was below that statement would cause issues. There are some php declarations that affect the entire file, like strict_types, that would need to be handled for this. I _think_ they can be stripped out when flattening, I don't think they are common in view files and there's no need to keep them in production use. (I love assuming things.)

So, assuming that we need to keep the context and keep as much backward-compatibility as possible, then I think we would need to wrap every view file in a function, similar to how javascript code is sometimes wrapped in a `(function() { ... })()` to avoid polluting the global scope. This, however, becomes a very fun (for weird definitions of "fun") activity that is slightly too complex to do in a quick issue reply.

**Comment by danilopinotti** [comment]
You're right. 
About the article, some things I did not agree with, but the 'flattened' views seemed to make sense (at least in my head).
It really is not so simple taking into consideration cases as recursion. Maybe, if you think better, some things we could handle, like the layout construction (extends) or non-recursive views. But in fact it is not something simple.
Thanks for the feedback and for sharing your knowledge.

**Comment by garygreen** [comment]
@sisve 

> I think we need to figure out where the problem is. Is it code execution, or file system access? The file system (and parsing) will probably be better with PHP 7.4's preload functionality, but it wouldn't speed up the code execution.

PHP preload functionality won't be of any help here because it can only preload classes, interfaces, etc. Basically, it has limitations. See here for more info: https://wiki.php.net/rfc/preload
