### ISSUE TITLE
Eloquent::insertMany() or similar method for multiple inserts setting defaults values like timestamps.

### ISSUE THREAD

**Issue by drnkwati** [laravel/ideas#1413]
Developers far back as 2013 have raised issues about inserting many records using eloquent.
I too came across the need for this as well so am reopening the issues with a suggested solution i have been using. I wish @taylorotwell and developers can consider including in the framework.
Here in this issue at
https://github.com/laravel/framework/issues/1295
Taylor suggested using the query builder for this.
Eloquent::insert() does the trick, but the following errors may occur:

1. Un sequenced columns will raise an exception, they must be in the right order for it to work.
2. Timestamps on these records are not set.
    Here is my suggested solution:

`
 /**
     * Insert new records into the database.
     *
     * @param  array  $records
     * @return bool
     */
    public function insertMany(array $records)
    {
        $fillable = array_map(function ($value) {return null;}, array_flip($this->getFillable()));

        foreach ($records as $key => $row) {
            $records[$key] = array_merge($fillable, $records[$key]);
            ksort($records[$key]);
        }

        return static::insert($records);
    }

`
If we can improve this or provide better alternative solution build in eloquent core, that sets any default attributes like timestamps etc. that will be great.
thanks

**Comment by sisve** [comment]
It's not clear, by reading this idea, what the actual problem is and how your idea solves that problem. How does your code set the timestamps? 

The linked issue talks about model events, does this idea attempt to solve that?
The linked issue talks about reading the generated model identifers, does this idea attempt to solve that?

**Comment by sisve** [comment]
I believe it would help your case if you explained your idea in here more than telling people to read other linked issues. That becomes more relevant when you only want to talk about some of the comments in the linked issue.

So, what are you trying to do? `User::insertMany(array($user1, $user2, $user3))`? Are we talking about model instances, or just arrays with data?

> If you look at my code above i have simple called the insert method but before that i ran a loop to normalize the data, while setting missing columns to null.

It looks like your code only adds missing fillable columns, not all missing columns. You would need to iterate through the entire $records array to get all seen columns, and then use these instead of the fillable columns.

Keep in mind that specifying a null value in a database call will use the null value, but not providing a value will make the database use the default value, which isn't necessarily null. Adding columns, even to add null, will change the behavior of the code.

**Comment by drnkwati** [comment]
thanks @nCrazed 
You have clarified much.  I was hoping for those events my self.

**Comment by mpyw** [comment]
Related
[[Proposal] findOrCreateMany · Issue #1695 · laravel/ideas](https://github.com/laravel/ideas/issues/1695)
