### ISSUE TITLE
[Proposal] Extend Mailable contract - require `build()` method

### ISSUE THREAD

**Issue by xkrupa12** [laravel/ideas#1466]
It seems it's not possible to instantiate `Illuminate\Mail\Mailable` class and send it via mailer, as within its `send()` method there's executed `Container::getInstance()->call([$this, 'build']);` that fails with:
`ReflectionException: Method Illuminate\Mail\Mailable::build() does not exist`

Based on [documentation](https://laravel.com/docs/5.7/mail#writing-mailables), developer should extend `Mailable` and implement `build()` method that holds configuration of the mail itself. 

Based on this, I'd suggest to: 
- extend `Illuminate\Contracts\Mail\Mailable` contract by adding `build()` method
- mark `Illuminate\Mail\Mailable` class as abstract and supply `abstract public function build(): MailableContract`

**Comment by ObliviousHarmony** [comment]
When an object is constructed by the container, or a method is called using it, the container uses reflection in order to inject your desired dependencies. Since you can't change the type signature of an already declared method, adding it to an interface or a parent class would remove the ability to add dependencies to your function declaration.

You'll note that this technique is used quite extensively throughout Laravel, and can also be used to great effect in your own code :)

**Comment by xkrupa12** [comment]
In this case, I don't see any problem having concrete `Mailable::build()` method signature as all the bindings can (and IMO should) be done using constructor rather than abusing method binding on a `build()` method - at least I've never encountered a scenario where I'd have to inject anything into it. I think that whole purpose of extending `Mailable` is to define dependencies in constructor and describe how to build an email in `build()` method.
If there's an issue with extending contract, I'm ok with leaving it as is, but since you're required to extend `Mailable` and implement `build()` method to use it, I'd suggest declaring the class as abstract as well as it's `build()` method. That way, instead of encountering `ReflectionException` you'd know right away that you need to supply the `build()` method and cannot use `Mailable` class directly.

**Comment by ObliviousHarmony** [comment]
Whether to use method binding or constructor binding is an exercise in personal preference. That said, I think the intention of having the Mailable's `build()` method use container binding has more to do with queued mail than piety. It allows for dependencies to be injected at runtime, instead of breaking the serialization of the Mailable.

**Comment by xkrupa12** [comment]
Thanks for your insight. I guess from now on it's more of a matter of personal preferences rather than anything else. 
IMO if a class is not supposed to be used on it's own and has to be extended, this fact should be clear from the beginning rather than throwing some kind of obscure exception, but I see your point. Even if I can't imagine myself in a situation that'd require me to leverage method binding over `build()` method, I guess it's possible.
