### ISSUE TITLE
Change env() to non-global

### ISSUE THREAD

**Issue by kawax** [laravel/ideas#1580]
Sometimes there is a package with env() global function.
Laravel project is broken if the env() is used.
As Laravel's env() is only used in config, is it ok to make it non-global?

src/Illuminate/Support/Env.php

```php
<?php
namespace Illuminate\Support;

class Env
{
    public static function get($key, $default = null)
    {
    }
}
```

all config files

```php
<?php

use Illuminate\Support\Env;

'name' => Env::get('APP_NAME', 'Laravel'),
```

**Comment by mfn** [comment]
Not only `env`, I think all global helpers should be actually made non-global.

- All are wrapped in `function_exists()` which is actually not working in a useful way because they're forcefully autoloaded by composer before any of your own code triggers
- global functions are destined to clash when integrating with other software, making integrating laravel in not-so-modern (i.e. legacy) application constantly a PITA
