### ISSUE TITLE
[Discussion] Why the AuthManager doesn't resolve using the Service Container?

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/ideas#1601]
I'm looking this code for the AuthManager and I'm very confused has to why it doesn't use the Service Container to resolve an instance of [the Guard Driver](https://github.com/laravel/framework/blob/5f8a72ffc373fd944cb50de641428ac854db0be7/src/Illuminate/Auth/AuthManager.php#L79-L98) or [User Provider](https://github.com/laravel/framework/blob/5f8a72ffc373fd944cb50de641428ac854db0be7/src/Illuminate/Auth/CreatesUserProviders.php#L24-L46). Instead, it manually instances them using the Services as parameters.

Shouldn't be more convenient to have the Service Container, and additionally use an array of parameters? And use this resolving method as a default for new Authentication Guards Drivers and User Providers? Currently you have to use only a Closure for both.

[From this:](https://github.com/laravel/framework/blob/5f8a72ffc373fd944cb50de641428ac854db0be7/src/Illuminate/Auth/AuthManager.php#L123):
```php
$guard = new SessionGuard($name, $provider, $this->app['session.store']);
```
to this:
```php
$guard = $this->app(SessionGuard::class, [
    'name' => $name,
    'provider' => $provider,
]);
``` 

Is there a much more big performance penalty for using the Service Container, at least, perceivable in production?

**Comment by ollieread** [comment]
I would imagine it's because it would be more expensive to resolve something that in theory should never change. You can override this behaviour by using the `extends()` method. 

You'll notice in the code that you highlighted, it [looks for a custom creator](https://github.com/laravel/framework/blob/5f8a72ffc373fd944cb50de641428ac854db0be7/src/Illuminate/Auth/AuthManager.php#L87-L89), so you can jump in before the default resolution.

The exact same can be applied for creating the user providers, as you'll see [here](https://github.com/laravel/framework/blob/5f8a72ffc373fd944cb50de641428ac854db0be7/src/Illuminate/Auth/CreatesUserProviders.php#L30-L34)

**Comment by sisve** [comment]
It already resolves from the container, that is what `$this->app['session.store']` does. However, `session.store` is not an interface, and cannot be resolved using php type hints. Changing the key to an interface name would probably break a lot of code.
