### ISSUE TITLE
'boolean' Validation rule to accept `on` as true

### ISSUE THREAD

**Issue by JackPriceBurns** [laravel/ideas#1664]
When using validation the boolean rule throws an error when a checkbox is the field being checked.

The ability to have the validation rule 'sometimes|boolean' would be great for checkboxes as you can then store that directly in the database without having to check if there is a checkbox value.

I'd be happy to make a pr for this my self.

**Comment by JackPriceBurns** [comment]
This can be kinda solved using the prepareForValidation() method we just discovered on the Request class.

for example 
```php
    protected function prepareForValidation()
    {
        $this->merge(['checkbox' => $this->has('checkbox')]);
    }
```

and now you can set your rules to
```php
    /**
     * @return array
     */
    public function rules()
    {
        return [
            'checkbox' => 'required|boolean',
        ];
    }
```

and in the controller which is super neat
```php
    $model->update(
        $request->only('checkbox')
    );
```

**Comment by jrbarnard** [comment]
Would this be doable by the accepted rule + nullable rule?

**Comment by martinbean** [comment]
@JackPriceBurns The value `on` isn’t a boolean, though. If you have a checkbox in your form, and it being checked (and value being passed as `on`) is “true”, then what happens if it’s left unchecked? It’s not going to pass _any_ value, and you’re boolean rule is going to fail because no value was passed at all.

No value is not a false-y value. Instead, have a hidden input with `0` as its value, and add a `value` attribute to your checkbox with a value of `1`. If the checkbox is checked, `1` will be submitted. If it’s left un-checked, then the hidden input’s value (`0`) will be passed instead. Both will satisfy Laravel’s boolean validate rule.
