### ISSUE TITLE
Loading resource once

### ISSUE THREAD

**Issue by Nuranto** [laravel/ideas#1669]
If you do:
```
$city = App\City::find(1);

$user->city; // $user->city_id == 1

$users->with('city');

```

The city with id 1 will be loaded three times, with one duplicate query.

That's actually a good thing most of the time, but for "static" resources like `cities`, it would be great to have only two requests (or better : only one but it seems complicated).

The ressource could be store in some global registry.

Could looks like : 

```
class City extends Model
{
      protected $staticLoading = true;
      protected $staticCompleteLoading = true;
}
```

When `$staticLoading` is true it would query the ressource, and store it into a registry. On next calls, it will send the resource from the registry instead of querying again.

`$staticCompleteLoading` could force to load the whole table at once even if not needed immediately. (if we know most/all of it will be loaded individually from different places)

**Comment by sisve** [comment]
I believe Hibernate and Doctrine calls this "first level cache" (mostly because there's also a "second level cache" before hitting the database). Doctrine implements this with an identity map, basically a large array saying `["city with id 1"] => $city1]`, so when someone wants city 1 they get the already loaded model.

This can quickly introduce complexity. What if the object is modified; should someone calling City::find(1) expect to get a value that differs from the database because some other code has modified it? What if they modify it without saving it, how are we reverting the changes?

I'm not expecting you to answer these questions, I'm just trying to expose the complexity. It would probably be easier to switch over to Doctrine than adding this to Eloquent.

**Comment by Nuranto** [comment]
I was not thinking of stored cache, but just memory cache that ends when the request ends.

And for modifications, I agree that for most resources, we don't want that behaviour, that's why it should be a by-ressource option. 
Also, we could introduce something like `findForceReload()` (with a more sexy name...) to answer the many needs.

**Comment by donnysim** [comment]
I think there's too many edge cases to just keep the fetched result in memory, as sisve said and also if someone cares about how much data they fetch:
```
$city = App\City::find(1, ['id', 'name']);
$user->city; // $user->city_id == 1 with all columns - id, name, country_id, created_at, updated_at etc.
$user->city()->first(['id', 'name', 'country_id']); 
$users->with('city:id,name,address');
```

They all fetch the same city, just different number of columns etc.. Keeping an instance in memory just because _it might_ match some further query seems expensive to me.

**Comment by Nuranto** [comment]
@donnysim I agree with you.
That's why I think about it as an option (false by default of course), when we know for sure it will be usefull for that specific resource on that specific app.

**Comment by mfn** [comment]
I don't want to sound pessimistic, but I can't see Eloquent (and to that extend: the Laravel team which decides what gets in and what not) ever supporting something like this.

Making it optional just makes it worse: easy to break and hard to notice.

I don't think Eloquents approach is the right architecture what you're looking for. Doctrine is, OTOH.
