### ISSUE TITLE
[Proposal] Choose driver to match cached routes

### ISSUE THREAD

**Issue by danilopinotti** [laravel/ideas#1694]
Recently I noticed that when I cache the routes (route:cache) my application consumes, on average, 2MB of RAM more than when the routes are out of cache (900+ registered routes) by each request. This can be a problem when there are multiple requests at the same time.

My suggestion is to a new configuration that can set the cache routes driver that could initially has two options: file and redis.

**file**: still like now

**redis**: Saves each route in the REDIS individually and the 'match' would be in REDIS itself. This way, we will be delegating the route match to the REDIS server without having to load all routes in the application.

**Comment by fragkp** [comment]
Have you tested route caching with redis?
I could imagine, that creating a redis connection decrease the performance.

**Comment by danilopinotti** [comment]
I don't test yet. For now, it's just an idea.

**Comment by garygreen** [comment]
> redis: Saves each route in the REDIS individually and the 'match' would be in REDIS itself. This way, we will be delegating the route match to the REDIS server without having to load all routes in the application.

The problem with this approach is your application will generally need all the routes loaded in order to generate route urls using `route()` or `action()` .

I've done some testing locally using route caching and it does indeed use a noticeable amount of memory when route caching is enabled, though rather bizrarely there doesn't appear to be any performance improvement when using caching. There's pretty much zero performance hit when loading around 200 routes - I get pretty much the same page load times when caching is off with the added benefit of lower memory usage.

I'm not sure when tests were done when the route caching feature was added, but in my tests it seems to have a negative rather than positive effect. Hmm.

**Comment by danilopinotti** [comment]
@garygreen 
What if the `route` and `action` methods call Redis to solve the route? We can think of a way to generate the cache key that includes these parameters.

Example:
`Route::get('/users/test', 'test@UserController')->name('users.test');`
The cache key may be: `action:test@UserController;name:users.test;http_verb:get;url:/users/test`
So, this key stores the serialized route.

We can also use tags (can be improved):
`Cache::tags(['action:test@UserController', 'http_verb:get', 'url:/users/test'])->put('name:users.test', $route)`

Additionally, we can make a fallback if the application can not connect to the redis server.

**Comment by danilopinotti** [comment]
Thinking now, route caching on files can become a problem when working with application instances on different servers

**Comment by garygreen** [comment]
Resolving routes from redis is going to be waaaaay slower than native PHP. Have you done any benchmarks?

Registering and resolving from 200 or so routes is lightning quick atm and uses hardly any memory (when routing caching is off), so I doubt there's much performance improvement to be made really. Maybe if you have 1000+ it becomes a concern - though in that situation I would probably break the application up into microservices/find a way to re-architecture your application to be capable of handling more requests - that's assuming routing is a bottleneck which I doubt it would be tbh.
