### ISSUE TITLE
[Proposal] Set the default authentication guard to "api" for the "api" middleware group.

### ISSUE THREAD

**Issue by elbojoloco** [laravel/ideas#1702]
Currently, the api routes use the `defaults.guard` authentication guard in `config/auth.php`, which out of the box is always `web`.

My proposal is to modify the `api` middleware to set the default guard to `api` instead of `web`, this makes implementing simple api authentication a lot more straightforward, as no custom middleware has to be written. 

```
// routes/api.php

Route::get('/user', function (Request $request) {
   return auth('api')->user();
});
```

This should be:

```
// routes/api.php

Route::get('/user', function (Request $request) {
   return auth()->user();
});
```

Defining the `api` guard while already in the scope of an API just feels redundant.

**Comment by koenhoeijmakers** [comment]
You're totally able to set the guard in the `routes/api.php` file, either by adding a group:
```
$router->middleware('auth:api')->group(function (Router $router) {
    // your routes here.
});
```

Or by adding `->middleware('api')` to the api routes in your `RouteServiceProvider`.

I'd use the first option as the latter makes it so that _every_ route in your `routes/api.php` file must have authentication.

In either case your call can be `auth()->user()` and you'll get the `api` guard.

**Comment by elbojoloco** [comment]
Thanks, very cool

**Comment by Iamt-chadwick** [comment]
Wonderful! This just fixed my issue.
