### ISSUE TITLE
Optional named parameters in routes produces wrong result

### ISSUE THREAD

**Issue by aimeos** [laravel/ideas#1752]
Laravel Version: 5.8 and before
See #7881 and #7892

Example route: /list/{f_catid?}/{f_name?}
Parameter: Only an additional parameter f_sort=price
Expected: /list?f_sort=price
Actual: /list/price

I've talked to @taylorotwell at Laracon.eu 2018 in Amsterdam about that problem. It can't be fixed in 5.x because it would break existing REST routing code (route /product/id? automatically gets populated with first parameter regardless of its name). Question is if it will get fixed in 6.0 where breaking changes can be made.

**Comment by rimace** [comment]
Hi again,
Thanks for your [post](https://github.com/laravel/framework/issues/29297#issuecomment-517278522), I was able to understand your intend and think this can be changed while staying backward compatible. 
Basically the `route()` method needs to check the names of the parameters and if it doesn't exist in the route definition, it appends the parameter using the query string. This way it should not break existing applications.
I'll prepare a patch the next days.

**Comment by sisve** [comment]
@rimace Could you explain how it wouldn't break existing applications as the original post describes?

> It can't be fixed in 5.x because it would break existing REST routing code (route /product/id? automatically gets populated with first parameter regardless of its name).

**Comment by rimace** [comment]
@sisve If I read [his pull request](https://github.com/laravel/framework/pull/7892) correctly then he wanted to move all optional parameters into the query string, which obviously would break old applications.
But if you look at this example, this behavior change he describes isn't needed, as it could be interpreted as a bug.
He has the route `/list/{f_catid?}/{f_name?}` and wants to link to if using this call:
`route('/list', ['f_sort' => 'price'])`. 
Now the bug here is that there is no `f_sort` parameter in the route definition (only `f_catid` and `f_name`). So instead of filling the `f_catid` with `'price'`, which is wrong anyway, we could also just fill every parameter, that is given in the function call but not defined in the route, into the query string.
I'm not sure if it is a good solution, but i guess better than filling the wrong parameter.

**Comment by sisve** [comment]
> So instead of filling the f_catid with 'price', which is wrong anyway, [...]

Laravel has done this for ages, the first parameter value goes into the first unfilled route segment spot. Changing this behavior will break things, no matter if it's wrong or unexpected.

**Comment by rimace** [comment]
Thought about it and I think you're right. It will break things if index names are spelled incorrectly. Other way would be to add an optional parameter `array $queryString` to manipulate that.

**Comment by aimeos** [comment]
@driesvints 
The problem has been fixed in Laravel 6: https://laravel.com/docs/6.0/upgrade

**Comment by driesvints** [comment]
@aimeos nice. Glad we managed to sort this out :)
