### ISSUE TITLE
UUID use binary(16) instead of char(36)

### ISSUE THREAD

**Issue by johnss** [laravel/ideas#1785]
i think the recommended/best practices to storing uuid in rdbms is by using binary(16) 

uuid is 128 bit represented in hexadecimal, in mysql you can use the following function to convert uuid to binary and vice versa, is_uuid to check if it is uuid or not
- UUID_TO_BIN
- BIN_TO_UUID
- IS_UUID

but i think it is better using hex2bin using php so i propose migration uuid() to change to binary as it will save more space and should be faster as some benchmark show binary are faster than char

you can see more how to store uuid in the link below
http://www.mysqltutorial.org/mysql-uuid/

**Comment by staudenmeir** [comment]
Unfortunately, that's not really possible. Laravel doesn't know if a column is binary and if it should be converted.

Of course, you can use this approach to store UUIDs for your own models and convert them with accessors and mutators.

**Comment by sisve** [comment]
I would like to add another view; this isn't as much as if Laravel knows how the column is persisted, but that it breaks compatibility with other systems, including existing raw/manual queries.

> i think the recommended/best practices to storing uuid in rdbms is by using binary(16)

I believe this to be wrong. Many other databases has a proper uuid type, like postgresql has the uuid type, and SQL Server has a guid type. This means that these databases support syntax like `WHERE id = '33555c1f-2211-4a7d-9f66-35cf5413444e'` natively, and you can copy/paste those queries around and they will continue to work since they are conforming to the sql standard. The only way to support this on databases without the proper data type is to store them as something that work identically which in this case becomes string values.

So, this suggestion would basically break existing non-mysql systems that has a proper uuid type, while forcing everyone into a binary format they need different sql functions to work with.

The problem here is that mysql, 2019, still don't have an uuid data type. If it's important to you to store uuids in a natively uuid-ish way, switch to a data storage that supports it (postgresql comes to mind...)

If you're interested in previous discussions, look into https://github.com/laravel/ideas/issues/350 (Store binary UUID in MySQL) and https://github.com/laravel/ideas/issues/645 (Add support for optimized binary UUID keys).

**Comment by johnss** [comment]
@sisve i think because mysql encourage to store 128 bit data in binary, mysql have no support for ipv6 but it have function to convert ipv6 to binary and vice versa the same as with uuid, because mysql has function to convert binary to uuid so i think mysql recomend storing uuid in binary there no need for native data type if it can do the same just with binary

**Comment by sisve** [comment]
How would this work in mysql 5.x that doesn't have these functions?

**Comment by johnss** [comment]
you can use pack()
https://stackoverflow.com/questions/2484267/16-bytes-binary-form-of-canonical-uuid-representation-in-php
or you can use this laravel package
https://github.com/spatie/laravel-binary-uuid
it is no longer maintained, but it should work for older laravel version, you should use its alternative specified in the readme for newer laravel version

**Comment by sisve** [comment]
I think that you need to read the other linked issues to understand how big this suggestion actually is. One reason this issue is large is because it will be implemented on a framework-level, and need to work for many different use-cases. There are a lot of places in the framework where uuid keys would need special handling, like foreign keys, routing, etc. Many of these places are discussed in the other issues.

Deciding on how to convert the string value into a binary value is a very small part of the problem.

**Comment by johnss** [comment]
it seems laravel will use string representation if the db does not support the native type, ipAddress() and macAddress() should use binary not char or varchar.

it is probably not worth the effort, because will break many things, also conversion from binary to string need to be performed which will probably lead to overall slower performance, search 8 byte binary plus binary to string conversion will be probably slower than just search 36 byte string, using char(36) probably faster as there is no conversion, if caching is used the binary will be faster, so the only advantage using binary is disk space
