### ISSUE TITLE
Pivot overrides

### ISSUE THREAD

**Issue by stancl** [laravel/ideas#1855]
I'm building an ecommerce system which requires a lot of data duplication into pivot tables. The `order_products` table needs the same `price` column as the `products` table. If the product's price changes, the ordered product's price must not change. I need to store the price of the product at the time of creating the order.

On my `Product` model, I have the following accessors:
```php
public function getQuantityAttribute()
{
    return optional($this->pivot)->quantity;
}

public function getNameAttribute()
{
    return optional($this->pivot)->name ?? $this->attributes['name'] ?? null;
}

public function getPriceAttribute()
{
    return optional($this->pivot)->price ?? $this->attributes['price'] ?? null;
}

public function getVatRateAttribute()
{
    return optional($this->pivot)->vat_rate ?? $this->attributes['vat_rate'] ?? null;
}
```

Out of these, `quantity` is the only purely pivot attribute. The other ones are present on both `products` and `order_products`.

It would be nice if I could just define
```php
public $pivotOverrides = ['quantity', 'name', 'price', 'vat_rate'];
```
instead of writing so much repetitive code.

**Comment by rimace** [comment]
And what `price` should be adverticed in `Product` of you have 5 `order_products`? The price of the last order?
The duplication makes sense, of course. But think of a case in which the company sends the customer some products for free as a gift for example. 
From a user perspective it makes much more sense to see the actual price of the product and the price it was sold.
So I would say that logic should not be hidden inside the model but defined in the views, which view should advertise which price. Otherwise you can never access the real product's price.

**Comment by stancl** [comment]
Closing this, because I gave up on using pivots in this case. Wanted to use them to give my users a better experience with Nova (attaching products to orders instead of attaching some OrderProduct resource that's hidden from the navigation) but Laravel's pivots introduce a lot of complexity when you need something more advanced.
