### ISSUE TITLE
Add a default order to Eloquent queries for consistent returned results

### ISSUE THREAD

**Issue by ajoy39** [laravel/ideas#1896]
This proposal comes from [this Stack Overflow question](https://stackoverflow.com/questions/58544826/laravel-pluck-didnot-return-sort-array-as-database/58545904#58545904).

To briefly summarize, running a pluck() directly on a query builder will return the plucked values in a random order if you don't add an orderBy yourself. While this makes sense if you think about it purely from an SQL standpoint, that is how SQL behaves if no order by is specified, it's inconsistent with how eloquent returns all other queries (sorted by primary key if no orderBy is presented). 

The root of the "problem" comes from the returned values, in both cases, being ordered by whatever SQL decides to order them by. The difference happens on the conversion to an Eloquent collection of Model instances. Simply adding a default `order by id asc` would make the results of the two queries consistent. 

It's a small thing, but it makes sense to me that if we're ordering one option by default,the other probably should be too.

**Comment by mfn** [comment]
👎 

I might return 100.000 models and pluck on them and not care about the order, but then it was decided to sort that automa*g*ically and my system wastes resources.

(note: don't get hung up about this use-case, it's about the philosophy behind)

Does not make sense to me. If you want a specific order, be explicit about it.

**Comment by ajoy39** [comment]
@mfn If you're using eloquent, they're going to be sorted anyway, you're just moving that sort operation from the database to PHP. If you want them completely unsorted you can use query builder. I don't propose we change the default sort order for anything but eloquent because that's the only place these records are already being sorted by default

**Comment by donnysim** [comment]
Well, as far as I understand and seen, eloquent does not sort them by default, it keeps the entries in the same order the database returns them. If pluck returns them in random order, then use any database tool and do `SELECT id FROM users` etc. and it will also return them in the exact same random order.
What happens is most likely that the entries were inserted in that order as in
```
 INSERT INTO table(id) VALUES (3)
 INSERT INTO table(id) VALUES (1)
 INSERT INTO table(id) VALUES (4)
 INSERT INTO table (id) VALUES (2)
```
so doing `SELECT id FROM users` returns `[3, 1, 4, 2]` because that's the order of the rows of database `id` index and it's faster to read them from the index rather than query the whole table.

**Comment by mfn** [comment]
>  If you're using eloquent, they're going to be sorted anyway

That's not true, any evidence?

> eloquent does not sort them by default

Exactly 👍

**Comment by ajoy39** [comment]
> That's not true, any evidence?

Yes, the stack overflow post linked in the original post. The query log showed no order being applied and if you called pluck directly on the eloquent query builder the records were returned in a seemingly random order, if you called ::all() first and then plucked they would be ordered by id.

The entire premise of my post is explained in that SO post, I’ve replicated the results that post saw on 2 different laravel apps including a production one. MySQL returns records in a non-determinant order if you don’t include an order by clause but once they were were placed in an eloquent collection they were in order by id.

**Comment by donnysim** [comment]
> MySQL returns records in a non-determinant order if you don’t include an order by clause but once they were were placed in an eloquent collection they were in order by id.

You do understand that `SELECT id FROM users` will return in random order while `SELECT * FROM users` will return in correct order (which is what was tried in the SO post)? Even `SELECT id FROM users WHERE random = random` can return in correct order because it won't be using the column index. IMO this is not an eloquent issue but more of misunderstanding of MySQL etc..

**Comment by mfn** [comment]
> The short answer is - this has nothing to do with Laravel or Eloquent.

Ack.

I re-read the SO answer https://stackoverflow.com/a/58545904/47573
> When an eloquent collection contains model instances, it's sorted by id unless you specify otherwise

First time I heard this. I also can't find this anywhere in the code. Searched in Eloquent\Collection and other cases where `\Illuminate\Database\Eloquent\Model::newCollection` is called. I don't think this is correct.
