### ISSUE TITLE
Policy for guards

### ISSUE THREAD

**Issue by malikzh** [laravel/ideas#1907]
Hi all.

I have an idea about laravel's guards and authorization policies. I don’t know if there was such an offer before me.

Ok, so what if we in `AuthServiceProvider.php` in value pass array of more variants of policies for guards.

When we make a new policy, we call command `php artisan make:policy --model=...`

So, we need add new argument to command `--guard=...`

And, after policy generate, first argument of any methods must be a guard model class.

Next, when we use authorizable trait or use `gate::allows`, etc.
with Dependency Injection principle we find out, what policy need use by first argument type.

I believe that this improves the structure of the application, because we can lay out policies in folders for the user. For example:

```
Policies/User/PostPolicy
Policies/User/CategoryPolicy
Policies/Admin/PostPolicy
...
```

Ok, i know about gates, but policies is a individual class and IMO that way preferred for  application with more than two guards.

How do you look at this?

**Comment by fletch3555** [comment]
I don't quite understand what you're suggesting.  I feel like you're conflating authorization (guards) and authorization (gates/policies).  There's really no reason one should know about the other, but they do work in concert in your app.

**Comment by malikzh** [comment]
@fletch3555 ok, let's i try explain it in code:

First step. Make a new Policy for Admin user:

```php
class MyPolicyForAdmin {
use HandlesAuthorization;

protected delete(AdminUser $u, $post) {
/// something code
}
}

class MyPolicyForManager {
use HandlesAuthorization;

protected delete(ManagerUser $u, $post) {
/// something code
}

}
```php

And make policy Client user:

```
class MyPolicyForClient {
use HandlesAuthorization;

protected delete(ClientUser $u, $post) {
/// something code
}

}
```

Next step. We need set `$policies` in `AuthServiceProvider.php` like this:

```php
protected $policies =  [
    MyModel1::class => [MyPolicyForAdmin::class, MyPolicyForClient, MyPolicyForManager::class]
]
```

When we check permisson like a `$admin->can(..)` or `$client->can(...)`, then appropriate policy will be used.

Why can't we do that?

**Comment by fletch3555** [comment]
Okay, so guards have nothing to do with it. You just want a way to have policies handle multiple User model types.

First thing coming to mind is if your `*User` models all extend from a common `User` class, you could do something like the following.  Not very elegant, but I think it should work, or at least get you much closer to your solution.

```
class PostPolicy {
  use HandlesAuthorization;

  protected delete(User $u, Post $p) {
    if ($u instanceof AdminUser) {
      // do something
    }
    else if ($u instanceof ManagerUser) {
      // do something
    }
  }
}
```

Having said that, I'm not certain exactly where Laravel is getting the `$u` that it6s passing into the policy method.  If it's basically just `Auth::user()`, then it might not return the correct user object.

As an aside, I would recommend reconsidering your auth scheme as a whole.  Instead of multiple guards and different user models, "Admin", "Manager", etc. should all be "roles" attached to a single "User" object.  This removes the entire problem described here, and makes much more semantic sense.

**Comment by donnysim** [comment]
What @fletch3555 said and I also think separating things is just adding unnecessary complexity to your app. Permissions should not care about user type and preferably what role he/she has - that just makes it a hell to refactor, imagine having to add another type of user, will you want to go through all your policies and most likely your code to support it? Ideally all it should do is check permissions (can this user access `users.index` etc.), nothing more, nothing less.

**Comment by malikzh** [comment]
@fletch3555 , @donnysim 
I thank you all for your constructive criticism and clarification.
