### ISSUE TITLE
Use a more sensible default JSON date serialization for Eloquent models

### ISSUE THREAD

**Issue by driesvints** [laravel/ideas#1940]
## Current Behavior

At the moment when you do this:

    $model->toJson();

You get this:

    {
        ...
        created_at: "2019-11-14 21:08:12",
        updated_at: "2019-11-14 21:08:12"
    }

## Proposal

Our proposal is to change it to this:

    {
        ...
        created_at: "2019-11-14T21:08:12.004740Z",
        updated_at: "2019-11-14T21:08:12.004740Z"
    }

Which is the default Carbon serialization if you do `json_encode(Carbon::now())` and conforms to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

## Key Benefits

The most obvious benefit is the full context of the timestamp. You get both Timezone context (`Z` which denounces `+0000` or UTC) and fractions in your timestamps. This is a great format for, for example, APIs to service timestamps. Consuming clients will perfectly know how to transform a timestamp in a given timezone of the user's browser, mobile phone or whatever they're using. They'll also be able to pinpoint times more precisely if that's needed.

Using a default like above also means that people building APIs don't have to format these instances anymore. They'll be available out of the box.

When you instantiate a new date in JavaScript for example, you can have a highly specific date instance with the proper timezone:

```js
new Date('2019-11-26T13:47:23.342983Z');
// Tue Nov 26 2019 14:47:23 GMT+0100 (Central European Standard Time) {}
```

## Counter Arguments

One of the biggest counter arguments is probably that Eloquent models don't have Timezone context at the moment when saving timestamps and that you can therefor assume that they're being saved as UTC. But the thing is that even by assuming UTC, it's better to be explicit and set the Timezone on your serialized format to also inform any consumer client that it is indeed UTC that's being served.

Another argument could be that timestamps atm don't support fractions. So returned serialized carbon instances for timestamp fields in your database would always have a fraction of 0. Again: it's better to explicit about this and use a sensible default like Carbon's instead of omitting details. 

## Implementation

My idea to implement this would be to adjust the behavior of the `serializeDate` method to convert Carbon instances to this new format. If you want to revert to the old behavior you can overwrite this method (as Taylor states below).

**Comment by taylorotwell** [comment]
It should be noted that any applications upgrading that wish to use the old behavior would add this to a base model class that all of their Eloquent models extend:

```php
    /**
     * Prepare a date for array / JSON serialization.
     */
    protected function serializeDate(DateTimeInterface $date) : string
    {
        return $date->format('Y-m-d');
    }
```

**Comment by driesvints** [comment]
@taylorotwell updated the implementation section with that in mind.

**Comment by billriess** [comment]
In our project we're doing this by having all of our models extend a `baseModel` that has this method:

```php
    // Overrides datetime object serialization
    protected function serializeDate(\DateTimeInterface $date)
    {
        $carbonInstance = \Carbon\Carbon::instance($date);

        return $this->isApiRequest() ? $carbonInstance->toISOString() : $carbonInstance->toDateTimeString();
    }
```

We have a private method that determines if the request is an API request.

**Comment by bredmor** [comment]
Considering that this change would be a net benefit in terms of detail available and the fallback implementation is extremely simple, I would find it hard to argue against this change.

My only concern is any issues arising from DST conversion. UTC itself never changes between daylight or standard time and this change introduces a *need* for calculation to where one may not have previously existed (e.x. a date is saved during PST and recalled during PDT). It is a minor concern, but perhaps should at least be noted in conversion docs.

**Comment by gregrobson** [comment]
My only concern is that it's possible to loose information by only storing UTC with offset. Echoing @bredmor's comments...

If you have values set in a model with time zones specified:
```
$modelA->created_at = new Carbon('2019-11-26 12:00:00', 'Europe/Paris');
$modelB->created_at = new Carbon('2019-11-26 12:00:00', 'Europe/Frankfurt');
```

They would both serilaize into ISO8601 with `2019-11-26T13:00:00+01:00` - but translating those values back to Carbon instances would not reveal the original timezone. This might not be a *common* occurrence, but it's a *possible* occurrence. e.g. you were populating a hidden field in a form with the IANA reference that the browser reports via JavaScript, or IoT devices in different countries were reporting data and had their IANA timezone set.

Carbon itself [serializes values with the IANA timezone description](https://carbon.nesbot.com/docs/#api-serialization).

Just to echo some guidance [from ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) on time zones:

> If no UTC relation information is given with a time representation, the time is assumed to be in local time. While it may be safe to assume local time when communicating in the same time zone, it is ambiguous when used in communicating across different time zones. Even within a single geographic time zone, some local times will be ambiguous if the region observes daylight saving time. It is usually preferable to indicate a time zone (zone designator) using the standard's notation.

**Comment by nokios** [comment]
Would this change require a change to how dates are stored in the database? Forgive my ignorance, but I am not quite sure how that would play out.  Would it need to be a different type of column?

Generally, I do like the idea, just wondering how it gets persisted.

**Comment by bredmor** [comment]
> Would this change require a change to how dates are stored in the database? Forgive my ignorance, but I am not quite sure how that would play out. Would it need to be a different type of column?
> 
> Generally, I do like the idea, just wondering how it gets persisted.

This proposed change is for JSON serialization, so unless you are storing the date in a JSON object field or using a storage adapter that relies on 'Model::toJson()` to collect data for persistence (perhaps a NoSQL document store?) there would be no difference for you.

**Comment by trevorgehman** [comment]
Since JSON serialization of Eloquent models is often used for API's, I think this is a great idea.

Here is an article I referenced when trying to decide on a date format for an API: 

[Based on thousands of APIs, what is the best approaches and format for handling timezone, timestamps, and datetime in APIs and Apps](https://www.moesif.com/blog/technical/timestamp/manage-datetime-timestamp-timezones-in-api/) 

The author points out that for APIs:

- Datetime data should always be returned in UTC
- There is a split between two choices for most common API's: ISO 8601 (`yyyy-MM-dd'T'HH:mm:ssZ`) or Unix epoch time

The author prefers ISO 8601 because it is (a) human-readable, and (b) avoids the ambiguity around whether the epoch time is given in seconds or milliseconds.

**Comment by driesvints** [comment]
@trevorgehman thanks, some good insights 👍

**Comment by kylekatarnls** [comment]
Hello. Counter-arguments about DST are irrelevant if things are properly handled. This change does not affect the storage, only the output. Calling a PST date during PDT is correctly handled in PHP:
```php
echo Carbon::parse('2020-08-01 00:00:00', 'America/Los_Angeles')->toJSON()."\n";
// 2020-08-01T07:00:00.000000Z
echo Carbon::parse('2020-12-01 00:00:00', 'America/Los_Angeles')->toJSON()."\n";
// 2020-12-01T08:00:00.000000Z
```

Now if you take those both date in your browser in Los Angeles and create JS `Date` objects with it:
```js
new Date('2020-08-01T07:00:00.000000Z')
// Sat Aug 01 2020 00:00:00 GMT-0700
new Date('2020-12-01T08:00:00.000000Z')
// Tue Dec 01 2020 00:00:00 GMT-0800
```

You get midnight for both.

Both your server and your browser perfectly know when are time changes.

Quick note about the 1-hour period after winter time begin. If you don't save dates in UTC, you get twice times from 1AM and 2AM (in Los Angeles for example) so you can't know if `2019-03-11 01:30:00` is GMT-0700 or GMT-0800 once stored, so if you save some messages dates as they come in America/Los_Angeles timezone (or any timezone with a DST), and check the list of messages sent between 1AM GMT-0700 and 2AM-0800 (2 hours range), you'll see the first hour messages and the second hour ones are shuffled.

So I would even say it's one more reason to save your dates (no matter where are your client or your server) in UTC and so this change of format will be the perfect fit to get your date unchanged from DB to client-side.

**Comment by kylekatarnls** [comment]
Now about data containing dates of different timezones (https://github.com/laravel/ideas/issues/1940#issuecomment-558773279)

The actual format does not reflect it neither. If you take Europe/Berlin and Europe/Paris, you'll see that they are 2 different timezone informations (different location and past history of the times differ) but if you append this to the date using GMT+0100, you lost the city information. Then if you pass the whole string to `new Date()` in JS, it will automatically convert it to local browser timezone no matter the timezone offset input. In any case, you'll need a function or a library that will request the 2 informations to be split (moment for example: `moment.tz("2014-12-01T12:00:00Z", "America/New_York")`). Here you can see that date and timezone are not 1 information, they are 2, so it makes sense to pass them as 2 different properties in API responses:

```php
$modelA->created_at = new Carbon('2019-11-26 12:00:00', 'Europe/Paris');
$modelA->created_in = 'Europe/Paris';
$modelB->created_at = new Carbon('2019-11-26 12:00:00', 'America/New_York');
$modelB->created_in = 'America/New_York';
```

Moreover, you also need 2 fields to actually store this precision in your database, so:
- Changing from 2019-11-26 12:00:00 to 2019-11-26T13:00:00.000000Z neither add or remove the timezone information
- There are better way to send a timezone information than mixing it inside the datetime string

I detailed this topic on medium:
https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa
https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164

**Comment by atymic** [comment]
I think this is an awesome idea. I always end up either writing resources to transform the dates to ISO in Laravel, or having a helper in javascript to parse the MYSQL date to ISO.

**Comment by v4lerio** [comment]
The proposal is a great idea 💡 👍

I find this very correct moving the source of truth to the record stored in the database, leaving the front end to deal user specific use cases (i.e.: conversion to user local timezone) using known JS libraries like the ones already mentioned above. 

Moreover, it is a handy feature for analytics use cases, in big-data applications, where this change will allow the database to be used (without further transformation) with third parties software or business intelligence integrations. 

In the API world, compliancy and best practices (ISO8601) are usually a good thing in the long term 😉

**Comment by kohenkatz** [comment]
I really like this idea, but I have one observation about it:

Many (most?) database engines have two timestamp types, one with time zone and the other without.

For example, in PostgreSQL, there are both `TIMESTAMP WITH TIME ZONE` and `TIMESTAMP WITHOUT TIME ZONE` types. Interestingly, Postgres actually stores **both of them** *without* the time zone. The difference is whether it does a conversion from the time zone you provided to UTC. More specifically, if your field is `WITH TIME ZONE`, you are telling Postgres that you care about the exact timestamp and that it should calculate the offset from UTC when it stores that timestamp. If your field is `WITHOUT TIME ZONE`, you are telling Postgres that you mean the generic idea of that particular timestamp but not at any specific location.

This is relevant, for example, if you would be making an application that works based on the business hours of a national (or multinational) company. If we say that every company office opens at 9am and closes at 5pm *local time*, we might want to store that deliberately `WITHOUT TIME ZONE` so that it is correct at the user's location without having to do any timezone conversion or worry about DST adjustments.

Based on that, it would make sense if this behavior could be determined based on the source of the timestamp in question - if we can determine that it came from a field that does not store timezone information, then it should be serialized without timezone information. If it came from a field that does store that information or if we are unable to determine where it came from, then it should include the timezone as proposed here.

**Comment by kylekatarnls** [comment]
> we might want to store that deliberately WITHOUT TIME ZONE so that it is correct at the user's location without having to do any timezone conversion or worry about DST adjustments.

Again: the proposed change will not require any DST adjustments you didn't require before.
And it's not because you might want this that this is the best way to achieve it and mostly the way Laravel should encourage. We're talking about a default output format you can change.

Times like 5pm/9am should absolutely not be date objects, don't save a dummy date, just the time numbers.

> using UTC times for that necessitates conversion based on DST

Nope, it doesn't as we're not talking about storage but about a format that your browser will easily reconvert properly, see my [first comment](https://github.com/laravel/ideas/issues/1940#issuecomment-558819783).

**Comment by crynobone** [comment]
Does `serializeDate` only handle `datetime`/`timestamp` format? 

The proposal is great, just the method name would throw me off guard for a little bit. 

Do we need a serialize method for `date` as well?

**Comment by kylekatarnls** [comment]
`serializeDate` handle any property you put in the `$dates = []` of your model which are by default the ones Laravel give you as Carbon instances by default.

**Comment by martbock** [comment]
The default behavior has bothered me for quite some time and i would absolutely appreciate this change. Big thumbs up! 👍

**Comment by crynobone** [comment]
@kylekatarnls 

> `serializeDate` handle any property you put in the `$dates = []` of your model which are the ones Laravel give you as Carbon instances by default.

```php
class User extends Model 
{
    protected $dates = ['birthdate'];

    protected function serializeDate(DateTimeInterface $date) : string
    {
        return $date->toW3cString();
    }
}
```

```php
class User extends Model 
{
    protected $casts = [
        'birthdate' => 'date',
    ];

    protected function serializeDate(DateTimeInterface $date) : string
    {
        return $date->toW3cString();
    }
}
```

Given the two scenario, what would be the value of `$user->birthdate` in both scenario?

**Comment by kylekatarnls** [comment]
You can try it with your Laravel 6 app. If you override `serializeDate()`, then this issue does not concern you, what will change is the default date JSONification when you don't specify `serializeDate()`

**Comment by driesvints** [comment]
I've sent in a PR for this here: https://github.com/laravel/framework/pull/30715

**Comment by ragingdave** [comment]
Since it's not mentioned at all here, how does all this affect/be affected by `Carbon::serializeUsing`. This is how I've been handling this sort of upgrade to ISO 8601 serialization and I've yet to have an issue? Does it instead break using that now since it's explicitly being serialized in the framework instead and would something simliar still be an option to change the serialization app wide?

**Comment by driesvints** [comment]
@ragingdave `Carbon::serializeUsing` is deprecated and we don't recommend using it anymore.

**Comment by kylekatarnls** [comment]
`Carbon::serializeUsing` affected only dates that are given to `json_encode` but models dates were never serialized this way, because `toArray()` converted it into string like "2000-01-01 00:00:00" (neither the default JSON serialization nor the ISO 8601).

`Carbon::serializeUsing` can only change the serialization of dates outside models in Laravel 6 and this will not change in Laravel 7. `Carbon::serializeUsing` will have the same effect.

If don't want the ISO 8601 as models dates serialization, you will need to override `serializeDate` (see https://github.com/laravel/ideas/issues/1940#issuecomment-558723063) and it's up to you to use the same serialization than the one you passed to `Carbon::serializeUsing` or not as in Laravel 6.

Note that the usage of `Carbon::serializeUsing` is discouraged because it won't only affect the Laravel JSON response you use but also the ones third-party libraries may use, and any call `json_encode` made internally to send via cURL or any channel you may not expect. That's why we recommend to exchange dates in the ISO 8601 and in UTC (a non-ambiguous universal format).

**Comment by ragingdave** [comment]
@kylekatarnls Maybe I'm doing something odd but I'm currently using the serializeUsing in a 6.x app in production right now and the dates of models are being serialized appropriately in the responses so I'm not sure what you mean by "outside models". That's mostly the reason I brought that up was because there doesn't seem to be any notes in changelogs for 6 or upcoming 7 noting that serializeUsing usage is no longer recommended. The only thing I can see is that it just disappears without a trace in the docs from 5.8 -> 6 but nothing is noted as being deprecated.

I'm certainly not trying to complain as the change in this idea (default serialization of ISO8601) is what I've been doing all along so it won't really change anything for me, but for others who might have a custom date serialization and not be following closely to the laravel/ideas would be left out of the loop and their apps could suddenly break without warning based on documented functionality that was just removed or broken (from their perspective). Especially since it does, at least in my case, still work as one expects in L6.x.

**Comment by driesvints** [comment]
@ragingdave serializeUsing is a Carbon method, not a Laravel one. So that's why you don't find anything in the changelogs/upgrade guide of Laravel. We removed its reference from the docs because Carbon has now deprecated it.

**Comment by kylekatarnls** [comment]
"outside models" means Eloquent properties you flagged as date (using `$casts` or `$dates` property of your model). Maybe you did not flagged those as dates, so you fall into the JSON serialization and so `Carbon::serializeUsing`. If so, you will still experience the same behavior in Laravel 7.

`Carbon::serializeUsing` is a Carbon feature deprecated since Carbon 2.0.0 (August 2018) so not directly related to Laravel, it's documented Carbon side and it's flagged `@deprecated` which should strikethrough the call in most IDEs.

**Comment by driesvints** [comment]
This was merged!

**Comment by ajcastro** [comment]
I think it would be nice to override the default datetime serialization in the AppServiceProvider 
something like: 
```php
Date::serializeUsing(function ($date) {
 return $date->format('Y-m-d H:i:s');
});
```
because some don't want to maintain another base model in their code especially for newly created laravel apps.

**Comment by kylekatarnls** [comment]
Nothing prevents you from adding this in your `AppServiceProvider`.

And the point was: JSON in Laravel 6 had de facto `Y-m-d H:i:s` in models and `Y-m-d\TH:i:s.vO` outside models. Having all your date serialized the same way in your JSON responses is way more consistent. Regarding 👍 / 👎 counts on this idea, it sounds clear that having `Y-m-d\TH:i:s.vO` as default will help more users. And it's logical to provide a more precise format that does not loose milliseconds and timezone by default and let other users trim dates if they want in `AppServiceProvider` as you suggest, but in your own application code.

**Comment by ajcastro** [comment]
I check the source code, I think there's no way to override it in `AppServiceProvider`. The only way to override it is through own `BaseModel` or a `Trait` where it overrides the the `serializeDate` method. 

I agree that the iso format should be default and I also like that. 

I am just thinking what if sometime for some reason you suddenly 
want to change it to different format then you will need to create a trait and use it in all models. 
Or maybe there will be no reason to change or use the previous format.
Because this should be really it.

**Comment by kylekatarnls** [comment]
`Date::serializeUsing(...);` can be called in any global (middleware, kernel, any service `boot` method).

> Or maybe there will be no reason to change or use the previous format.

JS in JSON stand for JavaScript, so I would say `Y-m-d\TH:i:s.vO` is the more standard and precise format for JS. For my part, I d'ont see any good reason to use `Y-m-d H:i:s` if you don't have some legacy constraints.

**Comment by heroselohim** [comment]
I have added the **Carbon::setToStringFormat** to cast also "toString" general calls. So this code is a **catch all** for me. Works with: toJson, toArray, toString, etc.

So all dates look like: 2020-04-20T16:41:59+00:00

```php
//	Your base model 

protected function serializeDate(\DateTimeInterface $date) : string
{
	return \Carbon\Carbon::instance($date)->toIso8601String();
}


//	/App/Providers/AppServiceProvider.php

class AppServiceProvider extends ServiceProvider
{
	...
	
	public function boot()
	{
		\Carbon\Carbon::setToStringFormat(\DateTime::ISO8601);
		\Carbon\Carbon::serializeUsing(function ($date) {
			return \Carbon\Carbon::instance($date)->toIso8601String();
		});
		
		...
	}
}
```

**Comment by kylekatarnls** [comment]
@heroselohim Due to some legacy mistake in PHP `\DateTime::ISO8601` you should use `\DateTime::ATOM` instead.
https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.types

The `\Carbon\Carbon::instance()` in `serializeUsing` is not needed `$date` is already an instance of `Carbon`.

And if you're using Laravel 7 the serializeUsing is not needed at all, as default JSON serialization already use an ISO-8601 string.

**Comment by heroselohim** [comment]
Thank you for the feedback! I'm using an older Laravel for this project and ignored this about L7.

**Comment by dillingham** [comment]
Would be nice if there was a way to keep the `.000000Z` for api and without for html inputs

https://github.com/laravel/framework/discussions/36794

**Comment by kylekatarnls** [comment]
```php
\Carbon\Carbon::serializeUsing(function ($date) {
    if (\Request::wantsJson()) {
        return $date->toJson();
    }

    return (string) $date; // Or any ->format() / translated ->isoFormat() or ->calendar() you want
});
```

**Comment by SupunKavinda** [comment]
Just leaving a comment in case this might help anyone. While ISO 8601 format is standard, the issue is with the query builder. We use the query builder for some complex queries and MYSQL returns timestamps in `Y-m-d H:i:s` format. So, the behaviour is inconsistent when using the query builder and eloquent models. So, we had to use this in the `AppServiceProvider` to override the default.

```php
public function boot() {
        Date::serializeUsing(function ($date) {
            return $date->format('Y-m-d H:i:s');
        });
 }
```

In Javascript, here's how we convert this string to a JS object.

```js
function mysqlToJsDate(mysqlDate) {
    var t = mysqlDate.split(/[- :]/);
    return new Date(Date.UTC(t[0], t[1]-1, t[2], t[3], t[4], t[5]));
}
```

Note that our application's timezone is UTC.

**Comment by kylekatarnls** [comment]
`Date::serializeUsing()` is for the JSON, so it should not be involved when using the query builder, both don't have to be consistent. On the contrary, there is no reason to mix the logic and unify both formats.

Side note: doing this you trim the timezone (the `Z`) from the datetime, this means you move from an explicit output that can be universally read by any system to a implicit timezone involving the front have to know it's UTC making it less interoperable, and it means you have to be sure every date object is already in UTC before it got converted to JSON, because you will have any date serialized this way, not only the date coming from your DB.
