### ISSUE TITLE
Policies require static functions

### ISSUE THREAD

**Issue by innoflash** [laravel/ideas#1958]
So in the ```AuthServiceProvider``` we define ```Gate```s in 2 different ways

```php
Gate::define('model.action', 'App\Policies\ModelPolicy@action');

Gate::define('model.action', [ModelPolicy::class, 'action']);
```

in the ```ModelPolicy``` class the first approach
```php
function action(User $user, Model $model){}
``` 
but using the second approach i get an error requiring that i make the method static
```php
static function action(User $user, Model $model){}
``` 

The problem now is i want to inject some dependancies in the Policy ```__constructor``` but then i can not access them in the ```static``` functions. 

Can you make the Policies **NOT** require some static function like the ```routes``` work

**Comment by martinbean** [comment]
@innoflash I’m confused. Policy classes _don’t_ require their methods to be static, which you can see from the stub: https://github.com/laravel/framework/blob/086c02a544af2870c52976408cded8cf59d7cf40/src/Illuminate/Foundation/Console/stubs/policy.stub

A policy should map one-to-one with an Eloquent model, rather than creating policies and then manually defining gates for those methods.

**Comment by innoflash** [comment]
Ok let me show you what i get here

* AuthServiceProvider
```php
    public function boot()
    {
        $this->registerPolicies();

        //sermon gate
        Gate::define('sermon.create', [SermonPolicy::class, 'create']);
        Gate::define('sermon.view', [SermonPolicy::class, 'view']);
    }
```

* SermonPolicy without static
```php
   public  function view(Ministry $user, Sermon $sermon)
    {
        return $user->id === $sermon->ministry_id;
    }
```

OUTPUT
```JSON
{
    "status": 500,
    "code": "SER_00",
    "message": "Non-static method FaithGen\\Sermons\\Policies\\SermonPolicy::view() should not be called statically"
}
```
### But when i add static to the function it works well
```php
    public static function view(Ministry $user, Sermon $sermon)
    {
        return $user->id === $sermon->ministry_id;
    }
```

### or rather i will have to use the string on the gates defining and it works without a static
```php
Gate::define('sermon.view', '\FaithGen\Sermons\Policies\SermonPolicy@view');
```
this works with default policy from stub

**Comment by martinbean** [comment]
@innoflash Again, why are you creating a policy, and then manually creating checks using the gate?

The issue is, you’re using policies wrong. Use them as intended:

```php
class SermonPolicy
{
    public function view(Ministry $user, Sermon $sermon)
    {
        return $user->id === $sermon->ministry_id;
    }

    // And other methods
}
```
```php
protected $policies = [
    Sermon::class => SermonPolicy::class,
];
```
```php
class SermonController extends Controller
{
    public function show(Sermon $sermon)
    {
        $this->authorize('view', $sermon); // Will invoke SermonPolicy@view method

        return view('sermon.show', compact('sermon'));
    }
}
```

If you are using [resourceful controllers][1], then you can authorise _all_ of your actions like this:

```php
class SermonController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Sermon::class);
    }

    // Your controller actions like index, create, store, etc.
}
```

I think you could probably do with reading through the [documentation on policies][2], as if you use them properly you’ll find you won’t need to make methods static. Your policy methods should be used _instead_ of custom-defined gate checks; not in conjunction with.

[1]: https://laravel.com/docs/master/controllers#resource-controllers
[2]: https://laravel.com/docs/master/authorization#creating-policies

**Comment by faithgen** [comment]
This is working, thanks

**Comment by innoflash** [comment]
This works, thanks lots

**Comment by martinbean** [comment]
@innoflash Cool. Glad you got it sorted 🙂
