### ISSUE TITLE
Extract model attribute casting to standalone class/component

### ISSUE THREAD

**Issue by fragkp** [laravel/ideas#2219]
Hey!

### Motivation
Often I came into situations where I have to cast some data (see use cases). For this kind of use cases, I create a custom `Casts` class which is mostly copied from the model's `HasAttributes` trait.
I think it would be really nice to extract this trait into its own class (`Illuminate/Support`) or component (`Illuminate/Casts`).

### Use cases
- APIs
```php
$data = Http::get('http://test.com/users')->json();

Casts::transform($data, [
    'id' => 'int',
    'created_at' => 'dateTime',
]);
```

- FormRequests
```php
class FormRequest
{
    public function rules()
    {
        return [
            'remember_me' => ['required', 'bool'],
        ];
    }

    protected function prepareForValidation()
    {
        $this->merge([
            'remember_me' => Casts::transformValue($this->remember_me, 'bool'),
        ]);
    }
}
```

### Closing
What do you think?
Do you have a similar use case?

**Comment by koenhoeijmakers** [comment]
I don't see why `Casts::transformValue($this->remember_me, 'bool')` would make more sense than `(bool) $this->remember_me`.

Same goes for your `$data` example, you'd typically map the result into a php object that respresents the state of said response.

**Comment by joelharkes** [comment]
I build my own laravel validator to overwrite and being able to transform input types.

Mostly models casts fix it but not when you have a 'array' type field on your model with additional payload.
Than instead of storing booleans it might store a number type or string type. Idem for all other types. Better to make sure in validation than needing extra casts afterwards.

I like the idea but I'd prefer if just validation would cast to the right type by default. Than you can use validation on API calls instead of only transforms.

**Comment by themsaid** [comment]
No plans for this at the moment.
