### ISSUE TITLE
Eloquent selectExists method

### ISSUE THREAD

**Issue by royduin** [laravel/ideas#2231]
So this:
```
->selectRaw('EXISTS(
    SELECT *
    FROM table
    WHERE something = anotherthing
) AS someboolname')
```

Can be written like `selectSub()`:
```
->selectExists(DB::table('table')->whereColumn('something', 'anotherthing'), 'someboolname')
```

**Comment by sshead** [comment]
Just had a use case where I would have loved a `selectExists()` or `addSelectExists()` method.

I have a `classes` table (model ClassModel due to reserved word) with a `hasMany` relation to a student `results` table, which has one row for each student enrolled in the class. So simplified, `results` looks something like:

```
| `id` | `class_id` | `student_id` | `mark` |
```

The `mark` is initially `NULL`. In my index view for classes, I have a delete button on each class, but it is disabled if there are any results already entered for that class (i.e. non-null `mark`).

I could just use a filtered count:

```
ClassModel::withCount(['results as filled_results_count' => (fn ($query) => $query->whereNotNull('mark'))])
```

and disable deletion if `filled_results_count` is non-zero. But I don't need to count records - and it would potentially be slower (though I haven't tested). It would be much cleaner to use:

```
ClassModel::addSelectExists(['has_marks' => Result::whereNotNull('mark')]);
```

The SQL for this would be something like:

```
select exists(
    select * 
    from `results` 
    where 
        `class_id` = `classes`.`id` 
        and `mark` is not null
) as `has_marks`
```

That would give me a boolean (if it's auto-cast) attribute `'has_marks'` on each of the returned ClassModel instances.

For now I implemented it with a `selectRaw`, though there are some drawbacks (doesn't auto-add `classes.*` to the select columns). And I also accept that the `withCount()` way isn't that bad, so it's not like I'm pushing hard for this. Just thought I'd make the case :-)
