### ISSUE TITLE
Laravel 7 - Logout specific user after updating

### ISSUE THREAD

**Issue by iammuttaqi** [laravel/ideas#2233]
As an Admin, I can register users. There's no way to register their own, only I can register them. So they can login with email and password that I given. But the problem is when I change their any of email or password they will be logged out immediately. How can I do that?

I tried this, but its not working-

`$getUser = User::where('id', $id)->first();
Auth::logout($getUser);`

**Comment by hicham-saddek** [comment]
Logically u can't do something like that,because the User informations are stored in a session in the Client's side not on the server,you might want to try to use login tokens instead of email password,like if a user is logged in it gives him a token key which basically can only allow him to stay logged for a brief time until the session is updated...

**Comment by ankurk91** [comment]
https://github.com/laravel/laravel/blob/7d62f500a789416738a7181d5217d33ca096db04/app/Http/Kernel.php#L35

**Comment by joelharkes** [comment]
If you store the user sessions in the database you can get all sessions of that user_id and than set user_id for that session to null.
