### ISSUE TITLE
Don't force developers to use blade, have PHP versions of blade functionality instead!

### ISSUE THREAD

**Issue by manyopensource** [laravel/ideas#2270]
For a framework of that popularity I would recommend not to depend on Blade, especially because not all of the PHP community would prefer it. There are people who would rather use another templating language or they could not use any of them. So if without blade we will not have the great amount of functionality, that would be quite sad! Thanks in advance!

**Comment by manyopensource** [comment]
I honestly can't believe that they haven't done it yet! Actually I really look forward to getting rid of blade from the framework, kinda silly wish I know! But being able to use **only php** is definitely great!!

**Comment by michaeldyrynda** [comment]
You don’t actually have to use Blade at all; you can just have `view.php` and write your templates using plain PHP if you prefer. 

Data is passed into these views in the same way it would be passed in to Blade templates.

**Comment by manyopensource** [comment]
> You don’t actually have to use Blade at all; you can just have `view.php` and write your templates using plain PHP if you prefer.
> 
> Data is passed into these views in the same way it would be passed in to Blade templates.

Can't find any reference how to use all the blade functionality (many of them begin with the @) on plain PHP!

**Comment by thannaske** [comment]
Not at all, you said you don’t want to use Blade, but any other templating engine, so of course you can’t use the blade syntax there.

Just write plain PHP and use the variables that are passed to the template.

**Comment by michaeldyrynda** [comment]
> Can't find any reference how to use all the blade functionality (many of them begin with the @) on plain PHP!

```blade
@if ($condition)
    // do the thing
@endif
```

Can be written as

```php
if ($condition) {
    // do the thing 
}
```

If you don’t want to use Blade, you can’t still use the Blade directives. If you want to use the Blade directives, just write Blade.

**Comment by manyopensource** [comment]
@michaeldyrynda what about not so obvious ones like `@component('layouts.app')`?!

**Comment by thannaske** [comment]
Just write plain PHP. You should be able to wrap something around the templating engine you want to use.

It‘s a bit weird to say you don’t want to be forced using Blade (and in fact you are not) and then ask for plain PHP integrations fo Blade features. Just my two cents.

**Comment by michaeldyrynda** [comment]
> @michaeldyrynda what about not so obvious ones like `@component('layouts.app')`?!

I’m confused; do you want to use Blade or not?

**Comment by manyopensource** [comment]
@michaeldyrynda How to write this list of blade commands in pure PHP:

- @section('sidebar')
- @show
- @yield('content')
- @extends('layouts.app')
- @section('title', 'Page Title')
- @parent
- @verbatim
- @hasSection('navigation')
- @production
- @env
- @csrf
- @method('PUT')
- @error('title')
- @props(['type' => 'info', 'message'])
- @push('scripts')
- @stack('scripts')
- @prepend
- @inject('metrics', 'App\Services\MetricsService')

And so on...

**Comment by happyDemon** [comment]
These are all very specific to blade, you'll have to recreate them yourself if you don't want to use blade.

It's strange that you don't want to use blade, but do have a need for its specific functionality.

Happy coding

**Comment by thannaske** [comment]
I simply don't get it. What are you even trying to achieve? Just use Blade and all its functionality (because that seems what you want) or implement the features you need on your own ... You won't get a plain PHP code example for all of those Blade functionality. Especially because you could just look into the Blade source code. Each of those blade directives has some plain PHP behind it (suprise).

**Comment by manyopensource** [comment]
@happyDemon, @thannaske Please read carefully the first comment!

**Comment by thannaske** [comment]
Read it quite a few times, still I'm not fully able to understand what you've written.

>  There are people who would rather use another templating language or they could not use any of them.

The first part of the sentence is clear, and it's something Laravel already allows you to do: If you use another template **engine** you can use its template language. I don't know what you want to say with the second part however. 

> So if without blade we will not have the great amount of functionality, that would be quite sad!

I don't quite understand what you are up to. Basically I read it like you want to use Blade functionality but without Blade, which is - as already stated - illogical and not possible. Either you use Blade for Blade functionality or you use the equivalent in some other engine. 

> Can't find any reference how to use all the blade functionality (many of them begin with the @) on plain PHP!
Blade functionality is nothing magical. Blade itself is implemented in PHP so you can use all the feature Blade offers you, in plain PHP already. Just look into the source code of Blade.

I would be very thankful if you could clearify your request if I didn't get it right.

**Comment by manyopensource** [comment]
@thannaske I'm not sure are you a laravel fanboy, who can't see outside of his, in this case laravel, scope, or not, but it seems that you can't comprehend how it's possible to use the functionality provided right now by Blade without the Blade!

**Comment by manyopensource** [comment]
> You won't get a plain PHP code example for all of those Blade functionality

I think this is the case - I don't want to implement some part of the laravel functionality otherwise why use frameworks in the first place! The functionality should be provided for pure PHP (it may not be the frameworks default way, but still should present equally).

**Comment by happyDemon** [comment]
Essentially this is already supported though.

Write a blade template and visit the page that renders it.

Once you've done that a compiled version of your blade template is saved in the cache directory.

This compiled template contains only php code (all blade tags are converted).

I think that's what you're searching for, you'll have to go through a few loops but essentially it's already supported.

If you think more people are interested in this you could send a pull request to the docs with your findings.

**Comment by thannaske** [comment]
> I'm not sure are you a laravel fanboy, who can't see outside of his

No need getting personal.

**Comment by tontonsb** [comment]
> @michaeldyrynda what about not so obvious ones like `@component('layouts.app')`?!

If you want to use other templating engine then use the other templating language with their equivalent of component. If you want  exactly the Blade features then use the Blade engine.

**Comment by Meeshalk** [comment]
@manyopensource 
You want to use blade features without using blade, simply write your own templating engine then. Why you asking Laravel to solve you specific problem.

I personally did not have any issues with blade because its a very good and well thought engine for templating.

Now to answer your issue;

1. The feature you want is already implemented and works very well as blade directive (maybe you need to understand them well)
2.  There is no need to have the same functionality AGAIN with PHP just because it can be done.
3.   If you really think this would be a good thing to invest your time then please go ahead and write the codes and share with all.

Questions???
1. Explain why this feature will be helpful to all or to laravel framework?
2. Will it have any benefits over the current solution (blade directives)? If yes, then what will be those benefits?
3. Will it have any performance gains? if yes then write a test to prove that?


I think laravel welcomes all constructive ideas very well, and that's the reason for its success as a PHP framework. For a developer there are two ways to develop a big application,
1. Go with what the framework provides out of the box and build a application without worrying about the things your framework offers.
2. Fight with your chosen framework for everything it provides for your convenience and waste your time dealing with its consequences, in this i'll suggest not to use any framework.


And as mentioned by @happyDemon let us know what you found in the cache files.

@michaeldyrynda @thannaske @tontonsb 
For someone who does not understand the actual issue because of the confusing title or/and description, @manyopensource wants the ability to write template in native php, using PHP functions. So, for **section** instead of ````@section('name') ... @endsection ```` it should be ```` section('name'){ ... } ````

@manyopensource I would like to hear from you and would like to know your answers so that we can discuss the possibilities for this feature.

Thanks
