### ISSUE TITLE
Decrease exception stacktrace verbosity

### ISSUE THREAD

**Issue by darklight9811** [laravel/ideas#2271]
The stacktrace contains laravel code, but 95% of the time, the bug, crash, exception, occurred on the client (programmer) end. Add an option in the env file to normal verbosity or high verbosity (that would include Laravel actual code).

## Why that?
Most of the time I have to search for what part of my code caused the exception throw, digging through laravel could is unnecessary 95% of the time, and only makes me waste time.

**Comment by thannaske** [comment]
The stacktrace is sorted by call hierarchy so the code that triggered the problem is on top. If you don’t scroll down you won’t see any Laravel-related stuff.

However you can’t just let information out that probably contain valuable information about an error that occurred. What if you strip out the error‘s source?

**Comment by darklight9811** [comment]
That's actually hardly ever the case, for example, if there is an error in a method call in a facade or model, I need to backtrace all the forward calls of laravel. If there is query error, I need to backtrace all the query preparation, usually 5 or 6 steps to find where I called that query. I need to see where my code caused the exception.

Enviada do Outlook Mobile<https://aka.ms/blhgte>

________________________________
