### ISSUE TITLE
Session vs Remember cookies - why does Laravel need both?

### ISSUE THREAD

**Issue by garygreen** [laravel/ideas#2395]
If you have a remember token cookie, you will basically be always logged in to Laravel, even if the main session cookie expires.

This makes me wonder why Laravel even needs both cookies. Essentially the remember token cookie is a long lived/permanent session cookie.

Would it make sense to just have one or the other, and not both? 

![image](https://user-images.githubusercontent.com/1702638/97187683-98bf2c00-179a-11eb-9ee1-758ca4f803da.png)

**Comment by paras-malhotra** [comment]
They're not interchangeable. You can't replace one with another.

The remember me cookie doesn't change when the session expires because it's a long lived cookie to stay logged in. So, it cannot do the job of a session cookie.

The session cookie is meant to map back session data, so it expires with the session. So, it cannot do the job of a remember me cookie, to stay logged in.
