### ISSUE TITLE
The Eloquent `getDirty()` method does not handle the casted attributes right now

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/ideas#349]
For more details:
 * https://github.com/laravel/framework/issues/8972
 * https://github.com/laravel/framework/issues/10735
 * https://github.com/laravel/framework/issues/15060
 * https://github.com/laravel/framework/issues/16823

**Comment by robclancy** [comment]
I love how this keeps coming up because Graham has closed all the issues. To the point it needs a master issue. He closes some saying "Duplicate" pointing to one he has closed for no reason ffs.

**Comment by quetzyg** [comment]
Standard.

**Comment by AkenRoberts** [comment]
It looks like cast checking for `isDirty()` [was added just a few days after](https://github.com/laravel/framework/pull/18400) @quetzyg commented.

**Comment by taylorotwell** [comment]
I think this is now implemented?

**Comment by HJBDev** [comment]
I'm not sure the current implementation has resolved this issue

In a project I'm currently working on (Laravel 6.2) I've had to implement the following workaround in order for the casting to work in `getDirty()`, otherwise something I've cast as an array comes through as a string. 

`'my_field_name' => 'array'`

```php
// following method is in a trait implemented by a model
public function getRawDiff()
{
    $changed = $this->getDirty();

   dump($changed['my_field_name']); // dumps a string

    foreach($changed as $key => $value) {
        if ($this->hasCast($key)) {
            $changed[$key] = $this->castAttribute($key, $value);
        }
    }

    dump($changed['my_field_name']); // gives me the array

    //...
}
```

If I'm reading that PR's implementation correctly, the first dump should return an array?
