### ISSUE TITLE
[5.4] Allows routes to match a subdomain

### ISSUE THREAD

**Issue by MarceauKa** [laravel/ideas#367]
Hi! Why do you think about subdomain matching in routes.

Concrete example:
```php
// My admin panel
$router->group([
    'middleware' => 'user.isAdmin',
    'as' => 'admin.',
    'subdomain' => 'admin.' // admin.myapp.com
], function($router) { /* ... */ });

// My API
$router->group([
    'middleware' => 'auth:api',
    'as' => 'api.',
    'subdomain' => 'admin.' // api.myapp.com
], function($router) { /* ... */ });
```

I need to do this on a WIP project and the current domain validation doesn't solve it and I don't to want to hardcode full domain in my routes file (eg: 'domain' => 'admin.mysite.com'). I imagine a new `Routing\Matching\SubdomainValidator` (acting like `Routing\Matching\HostValidator`) to do that.

What do you think? I can add code and tests for this new functionnality.

Implementation example:
```php
namespace Illuminate\Routing\Matching;

class SubdomainValidator implements ValidatorInterface
{
    /**
     * Validate a given rule against a route and request.
     *
     * @param  \Illuminate\Routing\Route  $route
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    public function matches(Route $route, Request $request)
    {
        $subdomain = $route->getAction()['subdomain'];
        
        return stripos($subdomain, $request->getHost()) === 0;
    }
}
```

**Comment by dwightwatson** [comment]
I would like to see something like this too, or otherwise subdomain routing where the route parameter is thrown away rather than passed into the closure/controller. My use case is wanting to test my API (with an `api.` subdomain) both in development and production.

With this set up, it only works in production. I have to change the domain to `api.example.dev` locally in order to use the API in development.

```php
Route::group(['domain' => 'api.example.com'], function () {
    //
});
```

My other throughs have been allowing `domain` to accept an array of domains (like `['api.example.com', 'api.example.dev']` or support a wildcard (like `'api.example.*'`).

**Comment by constb** [comment]
... or a regexp

**Comment by infernobass7** [comment]
I will agree with @dwightwatson that this will be nice especially if there is still support for 
```
Route::group(['domain' => '{domain}.example.com'], function () {
    //
});
```

**Comment by fernandobandeira** [comment]
@dwightwatson I've solved your problem of hard coding the domain name on my app by specifying it on the env file:

```php
'domain' => '{subdomain}.'.env('APP_DOMAIN'),
```

You could also change to use the APP_URL and just remove the protocol from it but I thought this would be cleaner. It's working for me at least however i would like this feature too 😄

**Comment by MarceauKa** [comment]
@fernandobandeira IMO, using env() helper in the route file is dangerous and cause problems in some cases (same thing using lang() helper).

Loot at my PR: https://github.com/laravel/framework/pull/18126

**Comment by fernandobandeira** [comment]
Well it's different than what you're proposing on your PR since we use this to get a dynamic subdomain, your PR isn't covering that, there's no tests at least that say otherwise...

For example
foo.example.com
'subdomain' => '{subdomain}'
there should be a parameter subdomain injected on the route with the value of 'foo'.

**Comment by SJMitchell** [comment]
I just used the environment variable that should differentiate for you:
`$domain = env('APP_URL');
    Route::domain('subdomain.' . $domain)->group(function () {
...`

**Comment by shamank** [comment]
I'm voting for this too. The env() implementation is really ugly but is the only way to deal with this at the time. When switching between environments I don't want to change two vars in the env file with basically the same thing instead of just one. And let's say that having an admin and a website in the same place or project is not an unusual thing. Please consider this feature request.

**Comment by bankorh** [comment]
There's a risk when using `env()`. If you run `php artisan config:cache`, the `env()` will always return `null`.

**Comment by skcin7** [comment]
One other problem with using `env()` directly in a routes file is you are unable to cache routes `php artisan route:cache` when doing this. Otherwise `env()` works but as others pointed out is extremely hacky and NOT a desired or good way to do it regardless.

I'm honestly amazed that Laravel doesn't support subdomain routing better, and being able to generate URLs to specific subdomains (or no subdomain at all). It seems so trivial but is such a huge pain in the butt. Honestly it needs to be supported.

**Comment by themsaid** [comment]
You can already use subdomain routing:

```php
Route::group(['domain' => 'admin.{domain}.{tld}'], function(){
     Route::get('/', function ($domain, $tld) {
        // ...
    });
});
```
