### ISSUE TITLE
Use translations in Notifications template + PasswordReset

### ISSUE THREAD

**Issue by barryvdh** [laravel/ideas#409]
Currently, the notifications are english only. For multi-language users, this almost always results in having to publish the notification file and add translations. Also, the password reset needs to be overridden.

What do you think about using translations in the notification template + password reset? Eg. something like this:

```php
<?php
return [
    'greeting' => 'Hey!',
    'error' => 'Whoops!',
    'salutation' => 'Regards,',
    'trouble-clicking' => 'If you’re having trouble clicking the ":actionText" button, copy and paste the URL below into your web browser:',
    'copyright' => 'All rights reserved.',
    'password-reset' => [
        'subject' => "Password reminder",
        'intro' => 'You are receiving this email because we received a password reset request for your account.',
        'action' => 'Reset password',
        'outro' => 'If you did not request a password reset, no further action is required.',
    ]
];
```

(Even for single-language apps, would still be a lot easier to modify)

**Comment by jbrooksuk** [comment]
I actually suggested this to @taylorotwell already.

**Comment by barryvdh** [comment]
So what did he say ?

**Comment by jbrooksuk** [comment]
> meh i wouldn’t worry about it

😂  unless I misunderstood that. But we IMHO we should have translations all the way through. I suggested a `notifications.php` translation file.

**Comment by garygreen** [comment]
People have tried to PR such a thing a few times, Taylor believes it's an over complication and you should just do it in your own app.

**Comment by jbrooksuk** [comment]
That does make the upgrade path harder though.

**Comment by dyegonery** [comment]
I think this should be reopen. Right now, it's almost impossible to use this feature if the application isn't in English.

**Comment by dakira** [comment]
@themsaid is **the** person who cares about localization. I'm sure he has an opinion! *wink* *wink*

**Comment by webmasterdro** [comment]
https://medium.com/@pedrolima_4201/how-to-translate-reset-password-email-in-laravel-b7fb7b79f996

It's impossible. Read this tutorial, we'll see how simple is to translate,

**Comment by dakira** [comment]
Can either @themsaid or @taylorotwell please comment if it would be a waste of time to start working on a pull request for this? Do you need more specifics?

**Comment by taylorotwell** [comment]
I'm open to this using the JSON translation stuff since we don't have to create a file for it by default.

**Comment by dakira** [comment]
FYI: I just started working on this.

**Comment by dakira** [comment]
I added a [pull-request](https://github.com/laravel/framework/pull/23885) and [documentation](https://github.com/laravel/docs/pull/4239).

**Comment by taylorotwell** [comment]
I think this is done?

**Comment by dakira** [comment]
@taylorotwell it is.

**Comment by drmax24** [comment]
Is it in laravel 5.6 already?

**Comment by dakira** [comment]
@drmax24 yes.. mostly. The default mail notification view is now translatable, the default ResetPassword notification isn't because that would add an unwanted dependency. To make ResetPassword translatable would require a bigger refactor (moving the notification itself to illuminate/foundation). In the meantime it can be translated quite easily by using the new toMailUsing() method. For now, though, ResetPassword is the only thing that is not translatable by just adding a json language file. If it were, we could have something like language-packs for Laravel.

**Comment by drmax24** [comment]
Can you reopen, please? If it is not done why do you close?

**Comment by dakira** [comment]
@drmax24 I didn't close this, Taylor did. Everything expected from this issue is now easily possible, so it can be closed, IMO. If I find the time, I'll write some documentation. I didn't get the feeling that making ResetPassword directly translatable is a priority and that anyone would welcome moving it to illuminate/foundation which is why I didn't propose it. You could help investigating the side effects of such a move, if you want to.
