### ISSUE TITLE
option for "same" validation to be case insensitive eg email:same_insensitive

### ISSUE THREAD

**Issue by codemonkeynorth** [laravel/ideas#520]
Laravel Version: 5.4

probably this may counts as a specific use case, but really would be standard... email addresses are presumably the same if the lowercase version matches. I guess I could just put in custom validation rule in the providers etc.

Would be useful to be able to pass a "same:email(insensitive)" rule or something like that though

thanks
j

**Comment by brayniverse** [comment]
Seems reasonable to expect it to be case insensitive.

For your particular use case, could you sanitise the data before validating to make sure it's already lowercase?

**Comment by brayniverse** [comment]
I say it seems reasonable, but in a different use case you may want the casing to be exactly the same. If you want to do something more complicated like declare case insensitive then I'd propose the following syntax.

```php
Rule::same('email')->caseSensitive (false);
```

Similar to how the new class based rules work in 5.4. (e.g from the docs; `Rule::in(['first-zone', 'second-zone'])`).

**Comment by sisve** [comment]
Case-sensitivity implies locale-aware checks. German has the "double-s" symbol ß (eszett) which should _probably_ be converted to SS when transforming to upper-case. That's probably the easiest way in this example since conversion to lower-case could be both "ss" and "ß".

This information aside; the issue talks about email addresses. These are _not_ case insensitive as a whole; they consists of two local-part + "@" + domain. From [RFC 5312, 2.3.11][1]; `the local-part MUST be interpreted and assigned semantics only by the host specified in the   domain part of the address`. This means that you should not assign meaning to the local-part unless you are the authority on the specified domain, this includes case conversion rules.

An example would be Gmail that ignores all dots in the local-part. There are also several mail providers that allow adding sub-addressing, as in "sisve+example@domain.com". Once again, you cannot say if the domain supports sub-addressing unless you're the authority. This means that you cannot tell if "sisve@domain.com" is the same as "sisve+example@domain.com" without knowing how domain.com treats their mail accounts.
 
[1]: https://tools.ietf.org/html/rfc5321#section-2.3.11

**Comment by brayniverse** [comment]
@sisve forgetting the email example for now. I wasn't aware of the locale specific edge cases, how would you recommend one does a case insensitive string comparison?

I presumed that if both values were converted to lowercase before comparison then both should be identical. However, if I understand what you're saying, `ß` could appear as `ss` in the user provided string; therefore `ßabc` should be equal to `ssabc`?

On a side note, I tried converting `ß` to lowercase myself and found it comes up as `b"ãŸ"`.

**Comment by sisve** [comment]
I recommend people to stay away from locale operations if possible. ;)

Functions like strtoupper/strtolower works with the current locale, which you first have to set in setlocale(). Except that, as comment on strtoupper mentions, you have to use mb_strtoupper(). Example: https://3v4l.org/cJ6MV

But I'm not happy with case conversion for the sake of comparison; it doesn't seem that mb_strtolower works either, https://3v4l.org/TfOSf

I have no other solution at the moment; the intl extension has a [Collator::compare](https://secure.php.net/manual/en/collator.compare.php) that should work, but I can't get my head around it at the moment. It seems to be case sensitive for my test cases, which I cannot figure out how to disable.
