### ISSUE TITLE
[SUGGESTION] Logic behind belongsTo function

### ISSUE THREAD

**Issue by lazicstefan** [laravel/ideas#531]
Even tho I am beginner in PHP world and Laravel, to me, logic about belongsTo function in Eloquent Model is a bit wrong.
For example, name of method inside one model could be anything for 'hasMany()':
```
public function anything()
{
return $this->hasMany('App\Something');
}
```
And 'Model->anything' will return collection of models.
In that case 'belongsTo', as documentation says, it determine foreign key by method name, so it MUST BE:
```
public function something()
{
return $this->belongsTo('App\Something');
}
```
**Which means, if I am not wrong, method name is always EXACTLY SAME as MODEL NAME passed to belongsTo() function.** 
In my logic, that's not right, belongsTo should take passed model name for determining foreign key if other is not specified as 2nd argument.
Maybe you think, wtf I am talking about but in some situation where table name contain 3 words 'first_second_third' (model of course FirstSecondThird), its not funny to return belongsTo with: 
`Model->first_second_third`
Shouldn't that be:
`Model->anything`

Sorry if my language is bad, or if I didn't understand something, or if there was already topic about this.

**Comment by Garbee** [comment]
You can't pass the class name, as the actual class name would be the FQCN (Fully Qualified Class Name) which would then need to be mangled to get an identifier. The method name is typically in some relation to the DB column name so that is more effective to use (and simpler/less buggy.)

Also at this point, there is no going back on this. To change the way the automated naming conventions work could break *tons* of applications that rely on it.

**Comment by lazicstefan** [comment]
About first part, I don't know that much about PHP, I am old .NET developer. What I see is that I pass string there (I know it could be Something::class) so I am not sure if you are right.

On the 2nd part of your answer, I don't it will break anything. Why? Because everything stays the same, except, name of method will doesn't matter anymore, old apps will still have name of method.

I could be wrong, I would like to learn more and refine my logic about this :)

**Comment by Dylan-DPC** [comment]
you can customize which foreign key it picks by passing in additional parameters

**Comment by Garbee** [comment]
That string is the FQCN of the class you want to relate to, whether you do it as a string or using the `::class` call it doesn't matter.

Not everything will stay the same for all setups, for example:
```php
public function item(): BelongsTo
{
  return $this->belongsTo(\App\Product\Variation::class);
}
```

What would happen in this case? You're saying it shouldn't be `item_id` now for the FK but instead what? `variation_id`, `app_product_variation_id`, something else? Converting classes into columns for people is non-trivial.

@Dylan-DPC The issue is about the automated naming, not about the fact that it can be manually overridden.

**Comment by lazicstefan** [comment]
Maybe you are right, but how 'hasMany' works?

**Comment by Garbee** [comment]
It's taking the *current* class and getting its name and appending with an `_id` suffix. Not the model being *related to*. That is a much simpler design decision to make for magic naming.

**Comment by lazicstefan** [comment]
Oh yes. That make sense.
On your question before, I think foreign key should be `variation_id`, but I guess I am wrong and it could be both? :)

**Comment by Garbee** [comment]
> and it could be both? :)

This is is the problem with the belongsTo relation naming. You could handle it various ways and it all depends on how the developer uses namespaces and builds their application.  The setup avoids this confusion by just taking the method name since that is the most indicative thing available to create a key from.

**Comment by Garbee** [comment]
Also, one model could `belongTo` another model in different contexts. So then what would you do if you name by the class name instead? For example:

```php
public function initialStatus(): BelongsTo
{
  return $this->belongsTo(Status::class);
}

public function currentStatus(): BelongsTo
{
  return $this->belongsTo(Status::class);
}
```

How would this situation be handled with naming the key magically by the class name? It would then have two different methods trying to use `status_id` for the key name even though they should be two distinct columns.

`BelongsTo` autonaming conventions simply can't change, it's too big of a break and wouldn't even make sense in different contexts.

**Comment by lazicstefan** [comment]
As I say before, I think default should be simplest thing. In case you want relation which is most usual thing, it will make sense in that case. I special cases that you are trying to find now, it have 2nd and 3rd argument to pass that additional parameters.

**Comment by Garbee** [comment]
I'm not "trying to find" cases, that type of thing is a typical situation that can occur.

Plain and simple, what you're asking for isn't the best way. As it leads to obscurity and will break loads of existing applications.

It's fairly safe to say this change will never get made because of that. Nor should it be changed, as what exists is direct and usable in more situations then the alternative being proposed.

**Comment by rs-sliske** [comment]
im struggling to see what the argument is for changing this

function *name* { return $this->belongsTo(*Model*::class); }

$this->*name* returns an object of type *Model* with an id of $this->*name*_id by default


eg 

class Post {
            function creator {
                       return $this->belongsTo(User::class);
            }
}

$post->creator;

will have the same result as doing

User::find($post->creator_id);
