### ISSUE TITLE
Configurable model directory

### ISSUE THREAD

**Issue by nospoon** [laravel/ideas#545]
Could we have some sort of global way of configuring a base directory for models, that would then be used by the generator? The default way of storing all models under App root directory is far from perfect for anything other than very small applications. 
I know it is possible to define the path in model name, but it becomes really cumbersome having to always specify the full prefix if we want a proper structure in the project.
This is just my opinion, but I think we should have a Models directory by default.

**Comment by Garbee** [comment]
You can extend the default generator and force the directory yourself if you wish.

Also, it being useful for anything "other than very small applications" all depends on your team and how you structure and think about things. 

This has been discussed numerous times before since the change was made. Thus far no options have been added so I doubt any will be now.

**Comment by FrittenKeeZ** [comment]
What I don't understand about the lack of a **Models** directory, is the literally every other class is neatly placed in their respective folders, so why should models be neglected?
I haven't seen a single project where it made sense to have models placed in the root directory, quite the contrary - imagine having 20+ models placed in the root directory solely because the proper structure isn't provided by default, and the developer doesn't know you actually *can* place models in their own directory... absolute hell I tell you!
So, apart from breaking backwards compatibility, what good reason is there to not have a separate Models directory?
If your structure relies on a domain-based approach, you could have the make commands implement --domain=Foo those use cases.

**Comment by phroggyy** [comment]
@FrittenKeeZ if the developer doesn't _know_ that you _can_ place models in their own directory, how did they end up getting a project that large without ever asking the question? I think seeing all your models in the root gives you a quick overview when you get started with Laravel, and makes it easier to get into using Laravel, caring more about learning Laravel and writing code, than about structure (which, by the time you have 20+ models, you surely would care about)

**Comment by Garbee** [comment]
> the developer doesn't know you actually can place models in their own directory... 

This is akin to being upset a contractor has been hand-driving bolts in for a fake wall when they could have turned around and picked up the bolt gun. Does it get the job done? Yes. Is it as efficient? No. In the end same results.

This is all a pure opinion piece. Taylor literally had a Models directory before and removed it to try and get people to **think** more before they just make a model for something. And to help them consider *how* they're naming their stuff.

You can spin around this wheel all day, but the discussion provides no true benefit with either outcome. It's actually fairly irrelevant.
