### ISSUE TITLE
Envoy on Windows

### ISSUE THREAD

**Issue by salarmehr** [laravel/ideas#571]
What does prevent Envoy to work in Windows? I can work on it to add Windows support.
Is deploying from Windows to Unix-based server supported?

**Comment by Garbee** [comment]
Probably the fact that scripting in Windows is dramatically different then Unix-based environments.

The only sane way to get all-system support would be to require Powershell and run envoy through that. But, there are still going to be inconsistencies with Windows commandlets that would need to be addressed.

**Comment by Garbee** [comment]
Oh, and you could try running it through "Ubuntu Bash on Windows" or whatever the compatibility layer Windows 10 has is. That should be capable of running Envoy right.

**Comment by salarmehr** [comment]
"Ubuntu Bash on Windows" acts as a separate OS (with its own set of software) Something I think is overkill to use PHP library that can work on Windows. gitbash is available on windows but yet I'm not sure if Envoy support it. Scripting need to be avoided as mush as possible for file systems actions. PHP provided functions the are cross-platform.

**Comment by Garbee** [comment]
Envoy takes advantage of PHP yes but there is still *scripting* that occurs inside of it. Since that is what you're doing is executing shell scripts.

Bash on Windows is not really a separate OS with its "own software stack". Yes, it does but it also co-exists with your Windows software and now can talk across the boundary.

>Scripting need to be avoided as mush as possible for file systems actions.

What? This isn't about filesystem stuff, it's about the physical commands that get executed.
