### ISSUE TITLE
[Proposal] Allow for CDN fallback 

### ISSUE THREAD

**Issue by badman-rodriguez** [laravel/ideas#576]
Allow for CDN fallback like ASP.net
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />`

`<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>`

Here it is explained
http://www.davepaquette.com/archive/2015/05/06/link-and-script-tag-helpers-in-mvc6.aspx

**Comment by m1guelpf** [comment]
@badman-rodriguez I think this is not Laravel's job...

**Comment by CupOfTea696** [comment]
This seems like a front-end issue, rather than a backend one, so I agree with @m1guelpf. You can just write some javascript to test the presence of stylesheets and scripts, using data attributes like `data-fallback-href`. 

Checking this in the back-end seems rather pointless & resource heavy to me, I don't think this has any place in Laravel.

**Comment by OwenMelbz** [comment]
@badman-rodriguez maybe you could explain the use case? If you're talking about the the default welcome blade, or auth templates, these are just starting points to overwrite, I don't think anybody assumed you'd be using them without modifying them.
