### ISSUE TITLE
[Proposal] @dump blade directive

### ISSUE THREAD

**Issue by kleshch-s** [laravel/ideas#590]
I have created blade directive @dump and tried to create pull request, but permission error has occured.
I propose to add @dump blade directive. It can dump all available variables of the current view or user can specify a variable to dump.
It uses dump() funcion of VarDumper.
`@dump` to dump all available variables of current view
or
`@dump($var)` to dump specified variable
It outputs the following:
`@dump`
[image link](https://ibb.co/kN6d85)
`@dump($var)`
[image link](https://ibb.co/fN6d85)

In my opinion it's very usefull during development project.
Should I post code here or how I can add pull request?
Thanks

**Comment by sisve** [comment]
Wouldn't this just be a simple `<?php dump($var) ?>`?

**Comment by kleshch-s** [comment]
Almost. Additionally checking of var existing is required. And yes it is shortcode for ordinary `dump`.
But the main value of the directive is invoking without parametr  to take all available variables. They are defined in composers, controllers, or some packages - doesn't metter - if some variable is available for your view - you will see it by `@dump` directive.

The complete code is
```
protected function compileDump($expression)
    {
        if (!$expression) {
            return '<?php dump(collect(get_defined_vars()["__data"])->filter(function ($value, $key) {return substr($key, 0, 2) !== "__";})->all()); ?>';
        }

        $varName = ltrim(rtrim($expression, ')'), '(');
        return "<?php dump(isset($varName) ? $varName : null); ?>";
    }
```

**Comment by ShahidH** [comment]
It would be nice to include second param `@dump($var, true)`  which mean it would not exit/die the application after dumping.

**Comment by sisve** [comment]
@ShahidH It should _never_ exit/die after dumping, because that is not what the `dump()` function does. You're thinking of `dd()` which is dump+die.

**Comment by kleshch-s** [comment]
@ShahidH I agree with @sisve. But additionally I would like to add ability to specify several variables. Like the following:
@dump($var1, $var2, ...)
or 
@dump(['var1', 'var2'])

But first of all I need to know - how can I create a pull request to approve it. Should I assign this issue to someone?

**Comment by m1guelpf** [comment]
@kleshch-s You can fork the framework repository, make your changes and then create a pull request.

**Comment by jerguslejko** [comment]
Sorry, I do not find it useful. Why add custom directive for code that will be deleted immediately?

`{{ dd($_) }}` or `{{ dump($_) }}` as be used instead? Maybe setup a shortcut in your editor?

**Comment by royduin** [comment]
I think it's a nice addition to the framework, I'm currently using these directives: https://gist.github.com/cheelahim/e51d45f9c837254c8fe9 but renamed the `d` to `dump` to keep it in line with the helper.

No one created a pull request so far? Couldn't find one.

**Comment by sisve** [comment]
Does this functionality make sense? Will you ever have a `@dump` or `@dd` in production code, or is it only used during development? Isn't `<?php dump($var); ?>` enough for temporary debugging stuff?

**Comment by royduin** [comment]
It's just for rapid debugging / testing. Laravel does have a lot of useful helpers, so let's make them available in Blade with a simple directive. It will never make it to production or should be committed in a project but that's not a good argument if you ask me. In that case the `dd()` and `dump()` functions should be removed completely because those should never be used in production.

**Comment by ajcastro** [comment]
Also it is easier to type obviously. You can save your keyboard typingsm, lol.

**Comment by sleicester** [comment]
There is a specific issue at the moment, in that if you use `{!! dump($var) !!}` or `{{ dump($var) }}` and have run `composer update` recently this will pull in `symfony/var-dumper` version **3.4**, which changes its behaviour to return the dumped variable. As the above blade statements `echo` before the dump this now fails for none string values being dumped (probably why you would use dump).

Details of this can be found in this issue here:  [Var Dumper - Backwards compatibility error in 3.3.x to 3.4.0](https://github.com/symfony/symfony/issues/25248)

We do use this in production for an admin/backend area that allows us to confirm the output of web services as this display is completely fit for purpose.

I personally feel that a `@dump` directive would be a nice addition. It might be what I add myself as a `Blade::directive()` as mentioned above.

**Comment by 36864** [comment]
You can wrap it in a regular php block instead of {{}}.
```
@php
 dump($var);
@endphp
```
or simply `<?php dump($var) ?>`

**Comment by CupOfTea696** [comment]
Or use

```
{{ dump($var) . '' }}
```

**Comment by gilbitron** [comment]
Added a PR for this https://github.com/laravel/framework/pull/23364
