### ISSUE TITLE
[Proposal] Offering Renderable Objects

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/ideas#624]
Laravel has the concept of "Mailable" objects.
Now it can offer renderable objects for a handful of good reasons :

- Help developers to have smaller controllers, (Technically speaking, help them reach True SRP in the controllers.)
- Make their code reusable both for Json API and HTML producing apps.
- Caching page partials become significantly easier.
- Renderable objects are much easier to reuse from project to project.

I have created a proof of concept package for it.
remember, when I say a "Widget" there, I mean a "Renderable" object by that.

https://www.github.com/imanghafoori1/laravel-widgetize

**Comment by sisve** [comment]
There's a well-known architecture that describes this; [Hierarchical MVC](https://en.wikipedia.org/wiki/Hierarchical_model%E2%80%93view%E2%80%93controller).

> The largest practical benefit of using an HMVC architecture is the "widgetization" of content structures. An example might be comments, ratings, Twitter or blog RSS feed displays, or the display of shopping cart contents for an e-commerce website. It is essentially a piece of content that needs to be displayed across multiple pages, and possibly even in different places, depending on the context of the main HTTP request.

Have you evaluated HMVC and how it compares to your solution?

**Comment by imanghafoori1** [comment]
I have heard the term but do not know what exactly HMVC is...
Let me take a look at it.

**Comment by imanghafoori1** [comment]
It seems that HMVC is different in a few critical ways.
It tends to call other controllers from within another controller to fetch HTML. (which I do not like at all because it is eager loading)
but "widgetize pgk" fetches it from the views. so it lazy loads the HTML.

http://www.javaworld.com/article/2076128/design-patterns/hmvc--the-layered-pattern-for-developing-strong-client-tiers.html
https://inviqa.com/blog/scaling-web-applications-hmvc

**Comment by imanghafoori1** [comment]
Second, the widget controllers DO NOT render views and return HTML. That way they can not be used to feed json apis.
They just return the data. and it is the framework's (or library's) job is to get that data and render the corresponding view with it. According to the widget's configs.
This way widget controllers can be used to supply data for json APIs.

**Comment by imanghafoori1** [comment]
caching, cacheTagging, minification
are also handled behind the curtains by the library
but HMVC pattern has nothing to offer about them.

**Comment by sisve** [comment]
Your initial post mentions four things that this does;

1. Smaller controllers / Move towards single-responsibility-principle
2. Allow controllers to return both json and html
3. Caching
4. Reuse

I believe that caching should not be implemented in this proposal, but in a separate framework-wide proposal. I believe that it does not make sense to implement a caching strategy for widget-controllers only, but it should instead be available for all controllers, when built.

You mention a few other things; if it is the controller or the view calling the new code. This isn't really specified in your original post, so it would seem to be an implementation detail in your package. If this is important then it should perhaps be added to the specification.

Assuming we allow HMVC-requests from the views  (and ignore the caching stuff for now) wouldn't that entirely cover all the points of this specification?

This idea of sub-requests isn't new, it's already implemented by Symfony. See their documentation on 
[HttpKernel Component > Sub Requests](https://symfony.com/doc/current/components/http_kernel.html#sub-requests). 

> In addition to the "main" request that's sent into HttpKernel::handle(), you can also send so-called "sub request". A sub request looks and acts like any other request, but typically serves to render just one small portion of a page instead of a full page. You'll most commonly make sub-requests from your controller (or perhaps from inside a template, that's being rendered by your controller).

ASP.NET MVC calls these [child actions](http://haacked.com/archive/2009/11/18/aspnetmvc2-render-action.aspx/). 

This functionality already exists in other frameworks and to me it does not make sense that Laravel would invent something totally different. It wouldn't be that much work to get this to work with Laravel; you can send new request through the routing system and have them invoke a controller and return the html code from the view. See [my gist on a childAction blade directive](https://gist.github.com/sisve/13cb9438ff74eb21f676a8bc3dcd11a0) for an example.

I believe that small gist solves all of the points in your original specification (once again, I'm ignoring the caching). It allows you to have widget-focused controllers that you invoke from a view, or you can render them using ajax because the route is publicly accessible. You can have the widget html load other routes in the same controller that return json. Basically, it looks just like a normal controller (because it is).

Of course, my solution has downsides. All widget urls are currently publicly accessible. The routing system would need a way to limit requests to sub-requests only. I believe it would be a flag (isSubRequest) on the Request object, and something in the routing system that checks this flag.

And once again, I think that caching is out-of-scope for this issue. Automatic handling of caching should be implemented in a way that works for all controllers, not only specific widget controllers. If we were to build a cache system that works for all controllers, then it would also work for my suggestion of sub-requests.

**Comment by imanghafoori1** [comment]
>I believe that caching should not be implemented in this proposal, but in a separate framework-wide proposal. I believe that it does not make sense to implement a caching strategy for widget-controllers only, but it should instead be available for all controllers, when built.

Let me shed some light on the current __widget-cache__ in order to clarify it.
Currently, the cached thing is NOT the data produced by widgets-controller, In fact the resulting html of a widget first gets minified and then stored in cache. so it does not even re-render the blade files each time.

And the good old problem with caching traditional controllers that return a full response (a full page) is that many pages are included with user specific data (ex contents of shopping card... or their username) so the server has to create a new separate copy for each user, which grows very quickly in storage size,

**Comment by imanghafoori1** [comment]
And let me mention that widgets (although they may need to be called something else, not widgets)
can be used to present not only __Cached HTML__ but __Cached Json__ data as well,
(you just need to put a {!! json_encode($data) !!} on your .blade file)

If you have created SPAs you can clearly see that they force you to have such atomic controllers.
because client-side framework issue a get ajax request for each widget of the page separately and get json data.

**Comment by imanghafoori1** [comment]
I like your Idea, but it is not the responsibility the current Router to manage caching and internal api and etc. We need to have a route method to map urls directly to widgets.
```php
 Route::get('/api/some-url')->widget('SomeJsonWidget');
```

**Comment by sisve** [comment]
> In fact the resulting html of a widget first gets minified and then stored in cache. so it does not even re-render the blade files each time.

Why should this not be a framework-wide caching system? Why should this type of cache only work for widgets?

> And the good old problem with caching traditional controllers that return a full response (a full page) is that many pages are included with user specific data (ex contents of shopping card... or their username) so the server has to create a new separate copy for each user, which grows very quickly in storage size,

What about a controller that returns a cached response, except for a widget that has user-specific data? I can make up scenarios where a framework-wide cache would work well.

> ... Cached Json data as well, (you just need to put a {!! json_encode($data) !!} on your .blade file)

Are you saying that you return a view that just contains serialized json? Why not just build a proper api that  returns json to begin with? Is this specifically for the scenario when you need the json embedded into the html of the response?

> If you have created SPAs you can clearly see that they force you to have such atomic controllers.
because client-side framework issue a get ajax request for each widget of the page separately and get json data.

I'm not saying that the concept of widgets/components is wrong; I am arguing that your implementation is odd. Laravel can build this with the existing infrastructure using sub-requests, without creating a whole new setup of WidgetRenderer, Normalizers, HtmlMinifier, etc. 

`WidgetRenderer::renderWidget(...)` - This would be the the existing Controller > Action > View chain that renders html as usual.
`Normalizer::normalizeWidgetConfig(...)` - In my mind oddly named, since it's mostly about validating the configuration/parameters and substitute values for default values. Still, some of this, the controller- and view validation, already exists in Laravel if we use the existing Controller > Action > View setup.
`HtmlMinifier` - If this doesn't break stuff (which I presume it does since it uses regex...), why wouldn't this be a framework-wide thingie, perhaps even a middleware (or a blade compiler)? Wouldn't the entire Laravel application gain from producing minified html code?

> [...], but it is not the responsibility the current Router to manage caching and internal api and etc.

I'll ignore the caching, I believe caching is complex enough as a fluffy concept, it's even harder to implement it correctly at a framework level. I believe it is the responsibility of the router to manage internal api calls. The router routes, and this would be something that needs routing. The only internal part about these routes is that noone is expected to call them directly, like "internal" apis on websites. The router could block these with a 403 Forbidden if they come from the outside world. 

There's also the scenario when you want these accessible from the outside world, like _real_ lazy-loading widgets where javascript fetches the html code on page-load. That would be another request accessing the route to fetch the html to embed into the dom.


Perhaps it would be easier to grasp if there were some examples.

How would, for example, a widget look like if I wanted it to say `<form>Your email is <input type="email" value="{{ $user->email }}"><input type="submit" value="Save"></form>` and allowing the user to change the email?

In "normal" Laravel and using a sub-request Laravel you would
1. Add a view that contains the mentioned html code
2. Add the EmailController::getWidgetView action that pass the current user to the view.
3. Add the EmailController::setEmail action that persist the changes
4. Add a route to EmailController::getWidgetView
5. Add a route to EmailController::setEmail
6. Add a `@childAction('EmailController@getWidgetView')` to the page that needs the widget.

How would this proposed solution implement this?

**Comment by imanghafoori1** [comment]
>Why should this not be a framework-wide caching system? Why should this type of cache only work for widgets?
I do not say it is a no no to have framework-wide caching system. I like the Idea (if implemented nicely)

**Comment by imanghafoori1** [comment]
>Are you saying that you return a view that just contains serialized json? Why not just build a proper api that returns json to begin with?

Of course, I will add this feature in the next version of my package. but currently it requires that hacky solution to produce Json.

**Comment by sisve** [comment]
@imanghafoori1 What you've described so far seems to "read-only" widgets that only contains data. I say read-only in the sense that they are only read from the server and rendered, they do not do anything else. This is already available in Laravel using a partial view backed by a view composer. The view composer could cache the data any way it likes.

    @include('widgets.my-widget', array('foo' => 'bar'))

I initially presumed that a widget would be able to talk back to the server/controller that it came from. Am I incorrect in this assumption? That is why I am introducing widget-specific controllers and routes into this issue.

**Comment by imanghafoori1** [comment]
>There's also the scenario when you want these accessible from the outside world, like real lazy-loading widgets where javascript fetches the html code on page-load. That would be another request accessing the route to fetch the html to embed into the dom.

Of course, this will do the job
```php
 Route::get('/api/some-url')->widget('SomeWidget');
```

but not all site do this, so the solution should be very optional.

**Comment by nCrazed** [comment]
I am failing to see the benefit here. Caching aside, you can already have more or less self-contained widget modules without any special api for it:

All you need is a controller, template, view composer and a service provider that registers the routes and wires up view composer(s) to the widget's template(s). The application only needs to register the widget's service provider and add an `@include` to the layout template.

**Comment by imanghafoori1** [comment]
>I initially presumed that a widget would be able to talk back to the server/controller that it came from. Am I incorrect in this assumption?

No you are right. I am thinking about this for 3 months but still need more experience to implement a good solution for it.

The current implementation is not that much read-only. you can handle post request in the data method with a ``` if(Request::methodIs('post')){ . . . ``` we have done this in a recent project.

**Comment by sisve** [comment]
> The current implementation is not that much read-only. you can handle post request in the data method with a if(Request::methodIs('post')){ . . . we have done this in a recent project.

Wouldn't that catch cases when someone includes the widget in a view that is rendered as a result of a post request? It wouldn't necessarily mean that it was the widget that wanted to post something back.

**Comment by imanghafoori1** [comment]
@sisve @nCrazed 
About View Composers :
I have totally studied the view composers long before and the downsides of using composers made me create such a solution.

1- The worst thing about view composers is you never know which composer is attached to a @include not to mention other members of your team.

2- You have no way of passing data to the ```compose()``` method from your view.
They receive a \Illuminate\View\View object. so they can not be re-used to expose json data.
widgetize designed to provide fully freedom and resuability for widget-controllers.
```php
public function compose(View $view)
{
    $view->with('count', $this->users->count());
}
```

3- $view->with('count', $this->users->count()); this exposes the $count to all views not just the partial.
4- They offer is no cache.

**Comment by imanghafoori1** [comment]
>Wouldn't that catch cases when someone includes the widget in a view that is rendered as a result of a post request? It wouldn't necessarily mean that it was the widget that wanted to post something back.

it is not the end of the world, requires a little bit of code by developer to handle all these issues.
but any way I know the library should provide proper structure for post requests as well.

**Comment by sisve** [comment]
@imanghafoori1 regarding the view composers, you register your view composer for a specific view. 

> 2- You have no way of passing data to the compose() method from your view.
They receive a \Illuminate\View\View object. so they can not be re-used to expose json data.

That would be the responsibility of the controller; and the controller has already said "the user has requested a view, not json". A view composer never executes for requests that returns non-views.

> 3- $view->with('count', $this->users->count()); this exposes the $count to all views not just the partial.

The composer registered for `widgets.dashboard.email-widget` will only execute for that view. Your statement is only true if you register them using wildcards.

#### Regarding cache

You keep mentioning cache; and I'll keep mentioning my stance on the cache issue; I don't think that this issue should involve any caching at all. If we would implement a caching of generated html, then it should be implemented on a level which would affect _all_ controllers/views, not only those for widgets. (Still, it would have to be an opt-in). If only widgets get some kind of view cache, then you will see solutions popping up where people use full-page widgets just to use the cache.

A caching solution sounds like a separate proposal/issue that would sit somewhere in the router/controller-dispatcher and short-circuit the entire action and view invokation. It wouldn't be that hard to implement, you can do it entirely by overriding Controller::callAction. This would handle both allow you to cache responses without ever calling the action, the view, the view composers, and you could even cache json responses.

I imagine that you could implement caching as a middleware if you wanted, but that would be slightly harder since I believe only the controller has enough context to determine the max-age of the response, and other important aspects of it.

**Comment by imanghafoori1** [comment]
>3- $view->with('count', $this->users->count()); this exposes the $count to all views not just the partial.
 
I mean the $count variable is available outside the intended partial. for example in other partials or the extended layout.

**Comment by n0rz** [comment]
Your point is thought provoking, allow me to retort: 
https://www.youtube.com/watch?v=8iO5-ic0Ug4

**Comment by imanghafoori1** [comment]
@n0rz Thanks about your retort
