### ISSUE TITLE
slack notifications

### ISSUE THREAD

**Issue by hirenkeraliya** [laravel/ideas#880]
Please add this facility to the laravel notification.
For attaching files to the slack notifications.
Have any way for this or not?

**Comment by cr0wst** [comment]
Currently, this is not possible because Laravel uses the [Incoming Webhooks](https://api.slack.com/incoming-webhooks) service which is limited to messages.  

In order to upload files, Laravel would need to use the [Slack API files.upload method](https://api.slack.com/methods/files.upload) which would require different authentication.

It is possible to display images using `SlackAttachment` via
```php
$message->attachment(function (SlackAttachment $attachment) {
        $attachment->title('Sample Image')
            ->image('<url to sample image>')
    });
````
however, this would require uploading the image somewhere else, and does not provide an avenue for file attachments.
