### ISSUE TITLE
[Proposal] Add chunkReducing() in query builder.

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#888]
Consider this query:
```
User::whereNull('is_enabled')->chunk(1000, function ($users) {
  foreach ($users as $user) {
    $user->is_enabled = 1;
    $user->save();
  }
});
```

Only half of the users records will be processed because chunk is issuing offset-limit in its query.
So my proposal is like this. Currently I created it in a scope query, but we can put it in the eloquent/builder core.
```
public function scopeChunkReducing($query, $perPage, $callback)
{
    $info = new Model([
        'page'       => 1,
        'counted'    => 0,
        'total'      => $query->count(),
        'percentage' => 0,
    ]);

    while ($info->percentage <= 100) {
        $items            = $query->limit($perPage)->get();
        $info->counted    += $items->count();
        $info->percentage = intval($info->counted / $info->total * 100);
        $callback($items, $info);
    }
}
```

Please see that an info data is also passed so you can display data in your commands. This can be also apply to chunk() method:
```
User::chunk(1000, function ($users, $info) {
  $this->info("  Running chunk #{$info->page}... {$info->counted} out of {$info->total} users ({$info->percentage}%)...");
  // do something
});

```

**Comment by deleugpn** [comment]
Why not just update via Query Builder? 

`User::whereNull('is_enabled')->update(['is_enabled' => 1]);`

This will be a single query with the same effect, except it won't fire events and it will be a lot faster.

**Comment by sisve** [comment]
@deleugpn Because he may want those events fired. Events may have a purpose, like a listener that unsubscribes them from a mailing list.

Anyhow, I understand the problem with chunk today; and it's specific for the case when your callback is modifying the objects so that they will no longer match the query chunk is executing on. However, this example implementation has the inverse problem; it will process the same items over and over again if the callback isn't changing the objects so they are no longer matching the query.

I believe that a better implementation would look something like ... (I'm making this up while writing this.)

    $lastId = 0; // default for id type, could be '00000000-0000-0000-0000-000000000000'
    while(true) {
        $pageQuery = clone $query;
        $page = $pageQuery->where('id', '>', $lastId)->orderBy('id')->limit($perPage)->get();
        if (empty($page)) break;
        $callback($page);
        $lastId = $page->max('id');
    }

The whole idea is that we do a "give me $perPage items after the $lastId I processed", over and over again, until there are no matching models. This means that we don't care if our callback modifies the models or not (as long as it doesn't change the id), our query ignores effectively ignores ids already processed anyway.

**Comment by deleugpn** [comment]
@sisve At first I didn't like your solution, but after giving it just a minute, it grew on me. With just a little bit of cleaning up, it seem like a good pull request. But then I found `chunkById` which seem to be doing exactly that. 

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Builder.php#L617

**Comment by taylorotwell** [comment]
See chunkById.
