### ISSUE TITLE
Allow overriding eloquent array attribute casting

### ISSUE THREAD

**Issue by robbytaylor** [laravel/ideas#972]
I have a [commit](https://github.com/robbytaylor/framework/commit/6d63a8b0af00f211e62cc4465d5b47d06821659d) which demonstrates what I'm proposing

The use case is that libraries exist to extend Eloquent for use with other database drivers such as MongoDB and ElasticSearch. Some of these (in particular I'm thinking of MongoDB) have native support for storing arrays without them needing to be encoded as JSON.

Currently, using a MongoDB driver I can't cast an array attribute as such in a model as it results in an error:

```
ErrorException: json_decode() expects parameter 1 to be string, array given
```

I could overload the `fromJson` method in the MongoDB Eloquent library, but that doesn't seem entirely right. I don't think a method called `fromJson` should need to check whether the value is already an array.

The change I've made above would allow Eloquent drivers for database with native array support to override the `fromArray` method to return the value as it is rather than attempting to decode from json.

**Comment by mfn** [comment]
I guess this begs the question: why is the "array cast" doing anything with json; I stumbled over this already (when deciding which cast to pick) and it didn't really make sense. As in: `array` feels wrong for json _when_ you have the `json` cast already.

Doesn't really help your cause except I think your change make sense but when accepted, the next guy/gal would change it back without knowing the reason behind this because it totally looks redundant without this knowledge.

OTOH, if the `array` cast would be implemented as actual array cast:
- it would make more sense, code-wise
- would break many apps
  (in that regard: your change _is_ sensible)
- and doesn't make much sense for eloquent because as long as PDO is used, a native array will likely never make sense here

I'm torn.

**Comment by robbytaylor** [comment]
I think the answer to your question would be that, for most database systems, developers have to store arrays as json.

Although Laravel doesn't support other database systems like MongoDB this change would allow other libraries to better support them. Following this change it would be possible for a model to work the same on databases which support arrays and those that don't by only changing the parent model class.

I think there's a wider change which could be made to the casting logic to check what format the data is in before attempting to cast it. That would address the issue of code appearing redundant, and prevent the array cast from doing anything with json data. I'm not sure though whether that would be excessive for a relatively minor issue.
