### ISSUE TITLE
The default behavior of only updating dirty attributes in `Model::update()` method is not a good idea. It may cause problems in concurrent scenes

### ISSUE THREAD

**Issue by eddiclin** [laravel/ideas#988]
These days I met a problem, lucky I resolved it today. It's about the dirty check of model for updating.
I have two processes which will update the same record by optimistic locking. I use `Illuminate\Database\Eloquent\Model::update()` in one process, but some values are ignored.

### Steps To Reproduce:

1. Create a table `machines` and a model `Machine`
``` sql
CREATE TABLE `machines` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `status` varchar(10) NOT NULL DEFAULT '',
  `latest_user_id` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
```
2. Init data: Insert one record
``` sql
INSERT INTO `machines`(id, status, latest_user_id) VALUES (1, 'idle', 1);
```
3. Run `HTTP API` in one process, `Background Service` in another process, as below
``` php
/*************************** HTTP API ****************************/
Redis::lock();    // pseudocode
$machine = Machine::find(1);
if ('idle' != $machine->status) {
    return;    // this machine is not idle, reject the request
}
sleep(10);    // just simulate do something
$machine->update([
    'status' => 'working',
    'latest_user_id' => 1,
]);

// some codes
```
``` php
/*************************** Background Service ****************************/
while (true) {
    $machines = Machine::all();
    foreach ($machines as $machine) {
        if (some conditions) {    // pseudocode
            Machine::where(['id' => 1, 'status' => 'idle', 'latest_user_id' => 1])->update(['latest_user_id' => 0]);
        }
    }

    sleep(7);
}
```
Because  `HTTP API` will be sleeping, the `latest_user_id` is updated by `Background Service` first , so the `latest_user_id` is 0 now, and it doesn't matter if I can update the `status` and `latest_user_id` together in `HTTP API`.
But I can only update the `status` field in `HTTP API` because of [the dirty check](https://github.com/laravel/framework/blob/40a8e352033e3225bed5fc99908938d4f15c727f/src/Illuminate/Database/Eloquent/Model.php#L625), the `latest_user_id` field is ignored.
Now the record in database is `id: 1, status: working, latest_user_id: 0`. It means a machine is working without a operator. So I met an error in subsequent business logic.

Finally I have to use `Illuminate\Database\Eloquent\Builder::update()` to resolve it.
``` php
Redis::lock();    // pseudocode
$machine = Machine::find(1);
if ('idle' != $machine->status) {
    return;    // this machine is not idle, reject the request
}
sleep(10);    // do something
Machine::where('id', $machine->id)->update([
    'status' => 'working',
    'latest_user_id' => 1,
]);

// fill the attributes manually
$machine->fill([
    'status' => 'working',
    'latest_user_id' => 1,
]);

// some codes
```

I'm not sure whether it is a bug, and whether the dirty check is a appropriate way for updating model.
Any ideas?

**Comment by sisve** [comment]
This sounds like something that transactions and locking would solve for you. That would block two requests from writing to the same row, and depending on the transaction level, even block two requests from _reading_ the same row. This is a "pessimistic locking", you take out a lock no matter what, which can block readers from accessing the data. You can use the lockForUpdate() method to do this.

Another approach is "optimistic locking" which can be implementing having a version column on the model. This is optimistic because it assumes there will be no problem and everyone behaves correctly. Every change to the model increases the version column, and the update should also filter on it. This way you know if noone has changed it (version was still the same and there was an updated row) or if someone has changed it (no affected rows, probably increased version).

    $affectedRows = Machine::where([
            'id' => $machine->id,
            'version' => $machine->version
        ])
        ->update([
            'status' => 'working',
            'latest_user_id' => 1,
        ]);

There's no built-in support for optimistic locking afaik, you would have to implement it yourself.

**Comment by eddiclin** [comment]
I write more code to make it more clearly, please read it again.
I have a HTTP API, and a background service. 
* HTTP API: The machine can be assigned for a user when its status is idle by HTTP API. 
* Background service: Because of some reasons, I cannot set the `latest_user_id = 0` when the `status` changed from 'working' to 'idle'. So I made a background service, it will check conditions, and set `latest_user_id = 0` every few seconds.

If I use "pessimistic locking" in HTTP API, it will affect the speed of the background service. I also cannot use "version optimistic locking" as you said, because the HTTP API just care the `status` value.  As long as the machine is idle, it must be assigned successfully.

In my opinion, there is no confuse with business logic between the sql of `code1` and `code2` without the dirty check.
Finally I use `Illuminate\Database\Eloquent\Builder::update()` instead to avoid the dirty check in `Illuminate\Database\Eloquent\Model::update()`. And fill the attributes of `$machine` object manually after updating.

**Comment by sisve** [comment]
> Because of some reasons, I cannot set the latest_user_id = 0 when the status changed from 'working' to 'idle'.

This sounds like a foreign key problem, and you should set latest_user_id to null.

> If I use "pessimistic locking" in HTTP API, it will affect the speed of the background service.

Yes, this is intended behavior. Instead of doing something wrong very fast, you're doing something right slightly slower. And the slower speeds are only shown when the http api and the background worker uses the same record at the same time as the web api. Controllering concurrency often means that some locks (and thus slow-downs) needs to be introduced.

The "optimistic locking" is fully possible to use in your case. Just update your code so the http api cooperates with the locking. That's why it is called optimistic, it thinks good of everyone involved and expects them all to work together. Anyone can misbehave and destroy the data since no actual locks are held.

**Comment by eddiclin** [comment]
The "some reasons" means the business logic of my project, not a foreign key problem. I think it may be complicated if I introduce too more business logic at first.
I just want to point it out that "the dirty check" is the default behavior for updating model, and it may cause problems in concurrent scenes if someone neglects it like me.
And is it a good idea to make "the dirty check" as a default behavior for updating model ?

**Comment by Patryk27** [comment]
Updating solely the dirty properties is a perfectly valid decision to me - if your code only changed one value during processing of the request, only that value should be persisted (changed) in the database. That's what I would expect and that's how majority of the ORMs work, I believe.

What you need is model versioning or a reasonable locking mechanism.

Updating the whole model would be a bad decision because, eg.:

- `Model::where([...])->update()` would need to do two requests instead of one: one `select` to fetch whole model + one `update` to update all its fields. But notice that between the `select` and `update` data could be changed by another thread! And thus you'd lose your first (that thread's) changes.

- what about large models? Say, with 30 fields?

Concurrent programming ain't that easy ;-)

**Comment by eddiclin** [comment]
@Patryk27 
Sometimes it is not suitable, as the above scene I described. 
And I'm not denying this behavior, but I hope that we can have a feature to disable or avoid the dirty check when updating the model object.

**Comment by Patryk27** [comment]
That would add an additional layer of complexity which one could have to maintain - it's not just a matter of doing `$fieldsToUpdate = $this->getDirtyOrAll();` (what about static `Model::update`? it's behavior cannot differ from `$model->save()`, which makes us go back to my "4 queries problem" above).

It's really _a lot_ of work for cases when the Eloquent isn't even the problem - you lack *model versioning* and doing `persist every field on each save() call` is not going to resolve that problem in a long-term.

**Comment by eddiclin** [comment]
I think I have explained [in this comment](https://github.com/laravel/internals/issues/988#issuecomment-364008672) why I cannot use "pessimistic locking" and "version optimistic locking".
And I think there are several ways to implement "optimistic locking". Besides versioning, some `where()->update()` based on the business logic could be "optimistic locking". Such as the code of my `Background Service`:
> Machine::where(['id' => 1, 'status' => 'idle', 'latest_user_id' => 1])->update(['latest_user_id' => 0]);

I prefer to discuss the rationality first, and then think about how to solve it by code. But now I don't know how to optimize it with the code.

**Comment by Patryk27** [comment]
You have a badly designed application (since you cannot automatically set `latest_user_id = 0` when changing status) - the only correct and readable solution to this problem would be doing that `update`.

You're trying to avoid one problem by introducing **a lot** of subtle new ones.
Even using triggers in this case would be better.

> If I use "pessimistic locking" in HTTP API, it will affect the speed of the background service.

Did you do benchmarks or rather you're thinking it will affect the speed? 
'cause [premature optimization is the root of all evil.](http://wiki.c2.com/?PrematureOptimization)
